### ISSUE TITLE
The Ok google command isn't working proberly

### ISSUE THREAD

**Issue by Bialuil** [htruong/crankshaft#125]
first of all, thank you for this cool project.

i have a little problem with the Ok google command. if i say "ok google" the "bling" sound appears and then it doesn't record anything, i cant't tell you how to produce this error because it sometimes dissapers after a few reboots. 

and then there is a second problem. My phone (Huawei P10 lite) is losing a lot of Power while connectet via USB to the Pi. maybe somebody can help me to solve this problem as well.

**Comment by chunky74** [comment]
The initial response to OK Google is the mic on your phone picking it up.  Crankshaft will then start to listen via the external mic that you have plugged in.  Spend some time investigating your Mic/connection.  I had to try the mic jack plugged in at various positions, as my mic jack has two conducting elements on the sleeve, but my soundcard is stereo and is expecting 3 conducting elements.  try doing an Audio test on your pi separately.  Cant help with your second issue - Sorry

**Comment by Bialuil** [comment]
Ok thank you i will try to fix it tomorrow

**Comment by nthanhtin** [comment]
For sencond problem, refer to this in openauto github: https://github.com/f1xpl/openauto/issues/86

If you don't want to read there. Basically set max_usb_current=1" in "/boot/config.txt" would give you 1.2A current output which is the maximum of thr rPi 3. I don't think that would be enough to charge new devices but your battery won't drop.
