### ISSUE TITLE
what is the lightning bolt for?

### ISSUE THREAD

**Issue by keredson** [htruong/crankshaft#19]
what is the purpose of the lightning bolt icon in the upper right hand corner?  is there a way to turn it off?

**Comment by floyduww** [comment]
The lighting bolt comes from the kernel for the pi.   It is telling you that it is currently being underpowered.  Make sure you have a good power supply and USB cable to power your pi.  2.5A is recommended for the raspberry pi 3.

**Comment by keredson** [comment]
if you're not opposed i created a PR for a FAQ section here.

**Comment by htruong** [comment]
I consider this issue solved :)
