### ISSUE TITLE
[csng] [bug] Crankshaft always starts in night mode even when rtc is disabled.

### ISSUE THREAD

**Issue by pumpkintechlabs** [htruong/crankshaft#200]
Fresh install of CSNG Pre-5 - always starts in night mode: loads night wallpaper and brightness setting. No RTC configured RTC_DAYNIGHT=0

**Comment by hawkeyexp** [comment]
Its fixed for next release since 8/12
[https://github.com/opencardev/crankshaft/commit/45700d1f91bb56d012b3635f7091cac59ab04b74](url)
