### ISSUE TITLE
Volume control

### ISSUE THREAD

**Issue by VittorioLu** [htruong/crankshaft#201]
Hi, the volume control does not work, I use Pre5-1 with GPIO 12 and 13 and set the file gpio2kbd.cfg with VOLUMEUP = 12 and VOLUMEDOWN = 13 but no result, I'm sure that the inputs 12 and 13 work fine because in DEV mode with "crankshaft gpio all "I see the change of state. Where am I wrong?

**Comment by Fotchman** [comment]
OK, here's the scoop: The WIKI located here: https://github.com/opencardev/crankshaft/wiki/Customizing-Crankshaft is correct overall about defining GPIO triggers. BUT the keywords and such are incorrect. The file boot/crankshaft/gpio2kbd.cfg maps/translates GPIO inputs to ASCII keyboard inputs. So to make the various triggers work, use the mappings from here: https://github.com/opencardev/openauto/blob/4fa68d1d7c977cccc2c4586b39f893cf9994113a/src/autoapp/UI/SettingsWindow.cpp#L237

For example, for Next Song to work on GPIO23, gpio2kbd.cfg should have the line

N 23

Pause would be:

C 21 # GPIO 21

Play would be:

X 6 #GPIO6

etc.

Makes sense once it is clear.

Hope this helps,

Aloha!
