### ISSUE TITLE
[CSNG][Feature Request] Option for verbose boot

### ISSUE THREAD

**Issue by pumpkintechlabs** [htruong/crankshaft#202]
On previous iteration of crankshaft (pre csng) I was able to have verbose boot at startup. Would be good to have an option that shows verbose boot without any splash screens if possible. The option can be set at boot.txt and will disable the splash screen and show verbose boot.

Cheers!

**Comment by hawkeyexp** [comment]
Hm.. what should be the benefit ? You can access the logs and will see what happens during boot.
Also you can disable the splash yourselve.

**Comment by pumpkintechlabs** [comment]
Saves having to access the logs especially if it's already installed in the car. On the other hand some people like myself like the verbose boot instead of splash screens - i disable them all the time when i run linux.

**Comment by hawkeyexp** [comment]
i think won't be included. If you need the output try removing the "splash" in cmdline.txt
