### ISSUE TITLE
[CSNG][Issue]Doesn't save changes in CS HW tab

### ISSUE THREAD

**Issue by mrfusion92** [htruong/crankshaft#204]
Just flashed the new Pre6 image (clean flash, not updated) and the settings in CS HW tab are not being saved. From my tests seems that all the settings from the other tabs are saved successfully.

I have attached the debug.zip made after save
[debug.zip](https://github.com/opencardev/crankshaft/files/2300422/debug.zip)

**Comment by hawkeyexp** [comment]
Have you checked the box on the right side ?

**Comment by mrfusion92** [comment]
Tried now. With the "exec setup on save" checked only timezone isn't being saved (tried again also with exec setup off), other settings are now being saved (also bt works).

[debug.zip](https://github.com/opencardev/crankshaft/files/2300521/debug.zip)

**Comment by hawkeyexp** [comment]
I have tested it and it works.
Can you try it in a ssh shell ?
Boot into debug mode and connect via ssh:
enter `crankshaft rtc ds1307`
let me know if you get any fail - you can check the timezone in /etc/timezone

**Comment by mrfusion92** [comment]
"crankshaft rtc ds1307" returns this error:

```
Crankshaft Management Tool v1.3.0 is executing command...

/var/lib/dpkg/info/tzdata.config: 337: /var/lib/dpkg/info/tzdata.config: cannot create /etc/timezone: Read-only file system
Reboot needed to activate!

Done.
```

**Comment by hawkeyexp** [comment]
please do a fsck on root partition if there are errors which prevents from switching between rw and ro

**Comment by mrfusion92** [comment]
Sure, will do when I will be at home. In the meantime, if there is a problem with the partition, why only the timezone setting fails to save?

**Comment by hawkeyexp** [comment]
It was a try but currently i could reproduce a possible problem - let me check it...

**Comment by hawkeyexp** [comment]
Update csmt with `crankshaft update csmt` - problem should be fixed.
Please report back and close issue if fixed.

**Comment by mrfusion92** [comment]
Works! Thank you!
