### ISSUE TITLE
[CSNG] Feature Request - Bluetooth output from Crankshaft to head unit

### ISSUE THREAD

**Issue by Fotchman** [htruong/crankshaft#207]
Good day kind devs! Love how the project is progressing. Bluetooth streaming from Galaxy S9+ to Crankshaft/RPi works great, no issue there. I would love to be able to output via Bluetooth to my head unit (since it doesn't have an AUX in). Is this, or will this, be possible in a future build? The input streaming seems redundant since for AA to work, you have to be cabled in via USB. Not complaining in the least, just seeing is this will be possible. Aloha!

**Comment by Maju3** [comment]
Already possible.
Pair your phone with your car stereo BT.
In crankshaft go to settings tab"audio".
Uncheck both channels(music,speech).

**Comment by Fotchman** [comment]
Hi Maju3 - thanks for the quick response. I did the steps outlined above, but I don't see how to pair Crankshaft to my HU. As a test, I'm trying to pair Crankshaft with a JBL BT enabled speaker. The JBL will send out a 'hello' message but expects the other device to begin the paring process. I'll check my HU tonight to see how it pairs (new in box). If it can initiate the BT response then all is well.

**Comment by Maju3** [comment]
No, you need to pair your PHONE to your cars bt stereo.
NOT crankshaft.

**Comment by Maju3** [comment]
That means you pair your samsung galaxy with your cars HU.
NO need to pair your phone with crankshaft.

**Comment by Maju3** [comment]
The bt pairing phone to crankshaft is for people who have NO bt car HU;)

**Comment by Fotchman** [comment]
OK, that's the 'feature' I was asking for :)  I didn't think it was currently possible but would be awesome to transmit BT audio to the HU. One less set of cables to deal with. The phone-to-Crankshaft pairing works fantastic.
Thanks again,

**Comment by Maju3** [comment]
Jup.
As said if you have a bt HU then there is no need to pair your phone with crankshaft.
Just pair your phone with your HU and you are fine.

**Comment by Maju3** [comment]
And in cs audio settings just uncheck music- and speech channel

**Comment by Maju3** [comment]
I think you can close this "issue" :)

**Comment by hawkeyexp** [comment]
As maju3 explained do a direct pairing of you phone with your car's HU. Cable and bluetooth is not really redundant cause phone calls are only possible via a bluetooth connection.
