### ISSUE TITLE
[DOC] WiFi connection

### ISSUE THREAD

**Issue by inspector71** [htruong/crankshaft#210]
Hi

I'd like to copy / paste and write a wiki document on how to connect with WiFi based on this thread:

https://www.reddit.com/r/crankshaft/comments/99py4c/wireless_connection/

Specifically, @FrankLaVerne's post here:

https://www.reddit.com/r/crankshaft/comments/99py4c/wireless_connection/e4t5g65

I would then modify the [Form factor section](https://github.com/opencardev/crankshaft/wiki/Getting-started-with-Crankshaft#form-factor) to include a note about WiFi connectivity to give context to the "- most simply via USB cable -" text.

I've cloned the WiKi repository and can use git on the command line but have yet to interact with a project based in github so could use a little hand there just to establish the editing workflow. I must admit, my style tends to be very iterative. In other words, I make lots of mistakes and often only notice them after publication :) Is anyone aware of a good offline markdown preview tool?

**Comment by hawkeyexp** [comment]
the wiki is open again - have fun :-)

**Comment by Codehhh** [comment]
@inspector71 Visual Studio Code has a pretty solid markdown editor built in, with some extensions to enhance support.

[Documentation](https://code.visualstudio.com/docs/languages/markdown)

**Comment by inspector71** [comment]
Thanks!

Funnily enough I was looking at VS Code just last week. 

Is it free of freemium?

Feels weird for me to be looking in the  Microsoft direction after a long time away from any heavy Microsoft use barring their operating systems. But I saw a few interesting plugins and a interesting web developer mention using it.
