### ISSUE TITLE
[CSNG] Pre8 randomly boots into DEV mode

### ISSUE THREAD

**Issue by dreamvictim** [htruong/crankshaft#216]
4-5 times so far using Pre8 on a normal boot has resulted in DEV mode being activated.

Switching off and on again boots normal.

**Comment by hawkeyexp** [comment]
possible caused by a gpio setting ? No reports until your one with this behaviour.

**Comment by dreamvictim** [comment]
I'm not using any gpio pins or setttings. I've installed pre8.1 so we'll see if it was just a glitch. If it doesn't happen again in next few days I will close.

**Comment by dreamvictim** [comment]
It's not happened again since Pre8.1 so i'm closing.
