### ISSUE TITLE
audio stutter and drop out

### ISSUE THREAD

**Issue by vair327** [htruong/crankshaft#217]
If you need support: Please post on https://www.reddit.com/r/crankshaft/ as this is a bug tracker, not a support forum.

Note: Reporting issues not based on official published builds will be closed without any comment.

- What phone do you have? htc 10

- What OS version? Andriod 8.0

- What crankshaft version?pre ng 8
[debug.zip](https://github.com/opencardev/crankshaft/files/2346663/debug.zip)

- Playing music (pandora, google music) or google reading text messages.

- Please provide any further information that you might find helpful if available.

- Starting with pre4: Boot into dev mode (can be selected in settings).
  Reproduce the possible bug. Create the debug logs by pushing the grey button on bottom of screen.
  Add the created file (/boot/debug.zip) to the issue.

  Warning: if you have configured wifi passwords they will be blanked by script during creation.
  We can't make absolutly sure you passwords are removed so do a personal check of the files inside the zip.

**Comment by hawkeyexp** [comment]
Have you the skill to verify this change is working for you?

https://github.com/opencardev/crankshaft/commit/ffb67612e264fce0ac2c0db510185e317f90fd6e

files to change:

/etc/pulse/daemon.conf
/etc/pulse/default.pa
