### ISSUE TITLE
why mouse doesnt work? isnt it supported?

### ISSUE THREAD

**Issue by Kingi-s** [htruong/crankshaft#222]
If you need support: Please post on https://www.reddit.com/r/crankshaft/ as this is a bug tracker, not a support forum.

Note: Reporting issues not based on official published builds will be closed without any comment.

- What phone do you have?

- What OS version?

- What crankshaft version?

- Steps to reproduce the bug, if you're planning to report a bug. Please indicate whether the bug is always repoducible.

- Please provide any further information that you might find helpful if available.

- Starting with pre4: Boot into dev mode (can be selected in settings).
  Reproduce the possible bug. Create the debug logs by pushing the grey button on bottom of screen.
  Add the created file (/boot/debug.zip) to the issue.

  Warning: if you have configured wifi passwords they will be blanked by script during creation.
  We can't make absolutly sure you passwords are removed so do a personal check of the files inside the zip.

**Comment by hawkeyexp** [comment]
should work but not specially tested cause it's designed for a touchscreen project.
Note: if touch is detected mouse pointer is hidden.

**Comment by Kingi-s** [comment]
i wanna test it out before purchasing a touch screen, do you have any ideas?

**Comment by Kingi-s** [comment]
i think i found reason, MY MOUSE WASNT ON.

**Comment by hawkeyexp** [comment]
lol

**Comment by Kingi-s** [comment]
i must be dumbest person on earth

**Comment by Kingi-s** [comment]
well now my mouse is on but and now its doing shit but cursor doesnt show up
