### ISSUE TITLE
String corrections in the Settings app

### ISSUE THREAD

**Issue by inspector71** [htruong/crankshaft#224]
Hi

I'd like to contribute by improving any typos I see. As I just edited the Settings Menu wiki page, I noticed a few things I could correct. I tried cloning the repo and `git grep`  but did not find some strings I was expecting.

Should strings in the Settings app be editable from the cloned app?

Thanks

**Comment by hawkeyexp** [comment]
? I could see some changes while resync wiki repo.

to bring up your local clone do a `git pull` inside which pulls latest changes and merge it to your local clone.

**Comment by hawkeyexp** [comment]
PS: the changes looks good :-) thx

**Comment by inspector71** [comment]
Whoops! I wasn't talking about the wiki repo :) I've gone back to editing the wiki repo via the web, for now. Glad you like the editing as well, thanks!

I'm referring to the actual Crankshaft source code. I thought I'd try and help out with small tweaks like ...

> Use big clock in classic (only if show clock enable)

instead of the current ...

> Use big clock in classic (only if show clock enable

But I cannot find that string in the source code.

**Comment by hawkeyexp** [comment]
Ups sorry misunderstanding :-)

It's loacted in the settings ui -> https://github.com/opencardev/openauto/blob/crankshaft-ng/src/autoapp/UI/settingswindow.ui (line 364 in current file)

**Comment by inspector71** [comment]
Oh wow, ok. No wonder I didn't find it. Wrong project! 😀 Thanks!
