### ISSUE TITLE
Hotspot breaks when psk is set to something non numeric. [CS-NG pre9]

### ISSUE THREAD

**Issue by tehniemer** [htruong/crankshaft#229]
when the hotspot psk is changed to something alpha-numeric instead of strictly numeric the splash screen sticks over the menu screen until you touch it, and the hotspot no longer is accessible.

**Comment by hawkeyexp** [comment]
This is not depending on numeric - could it be possible that you have special chars in your psk ? Try to add quotation marks:

`HOTSPOT_PSK="xyz"`

Don't use a "$" cause it's a command char in bash so it can break the script.

**Comment by hawkeyexp** [comment]
Break prevention added...
