### ISSUE TITLE
[CSNG] Google Assistant choppy and breaking up in "Native Audio Paths"

### ISSUE THREAD

**Issue by pumpkintechlabs** [htruong/crankshaft#230]
- Pixel XL
- Android 9
- PRE-7-8-9

- Connect the phone directly to car's headunit via BT. Uncheck both audio channels in OpenCarOS Settings.

- Especially noticeable after Android Auto just finish loading - even music playback can chop for a bit. When querying Google Assistant - its replies are very choppy and delayed. Noticed this behavior since PRE-7

**Comment by hawkeyexp** [comment]
If you have directly connected your phone via bluetooth to car's headunit not to cs nothing can be done cause cs has no interaction with it while audio stream is routed directly from phone to headunit.
