### ISSUE TITLE
Wi-Fi and mobile data

### ISSUE THREAD

**Issue by mishu28nmv** [htruong/crankshaft#231]
I can connect with the wifi function but I don't have internet then, so no spotify or tunein. Waze is working but offline I think.
Tried to mark the "switch to mobile data when no internet from wifi" function, but still no internet.

- Samsung Galaxy S7

- Android 8.0.0

- Crankshaft Pre9

**Comment by hawkeyexp** [comment]
Not every device can handle this dual connection. If you check reddit some devices are working fine with the current setup. There is no doc about the detailed config from google to identify which constellation allow both in a working case. The default scenario is the one or the other way - google is breaking this normal case.
I have the same effect but could identify a possible solution to get it working... But it's not really a cs problem...
I will keep the issue open but there is no way to solve it for all devices.

As i said in the wiki:

If it works, be happy. If not, there's nothing we can do, currently

**Comment by mishu28nmv** [comment]
> I have the same effect but could identify a possible solution to get it working... 

I know that there is not a problem from CS:NG.
I have 2 option on the 'switch to mobile data' function: normal mode and agressive. I will try them both.
Can you share your solution? Thank you for everything!

**Comment by internix14** [comment]
Well. Some phones need to be in developer mode. Or in xiaomi phones case. In developer settings you can activate an aggressive dual link. Try to see if Samsung phones got that

**Comment by hawkeyexp** [comment]
@mishu28nmv try to comment out the router option (3) in dnsmasq.conf - this seems to be an essential part in this case.

**Comment by mishu28nmv** [comment]
Thanks all. I will try everything

**Comment by mishu28nmv** [comment]
@hawkeyexp 
Do you mean this:

router
dhcp-option=3,192.168.254.1 ?

**Comment by hawkeyexp** [comment]
yes - comment it out...

**Comment by mishu28nmv** [comment]
I did those 2 lines with # symbol. I will mount and see how it goes :)

**Comment by hawkeyexp** [comment]
Have you tested ?

**Comment by inspector71** [comment]
Pretty surprised by this. My ASUS phone has never needed any configuration changes to do this. I just toggle WiFi and Mobile data and it's not an issue. Guess I'm just lucky,

**Comment by xHirscHx** [comment]
Just set this up its asking for password to conect to crankshaft.looked on forms can't find default or I missed it. Any help thx

**Comment by dreamvictim** [comment]
@xHirscHx 1234567890

**Comment by mishu28nmv** [comment]
> Have you tested ?

I think for me it's better just to plug the usb. I'm not using the wifi function anymore. Thanks for your support!!!

**Comment by hawkeyexp** [comment]
Ok than i will close issue.
