### ISSUE TITLE
[CSNG] [Feature Request] Extend the UI to take up the whole screen

### ISSUE THREAD

**Issue by pumpkintechlabs** [htruong/crankshaft#232]
Love the new tile UI it works amazing!
At the moment we have the black bar on the top with OpenCarOS and Build tag. In order to keep the UI clean it would be good to remove the black bar and extend the UI tiles and wallpaper to take up the whole screen (like it did before PRE-8) and in the Settings there can be another tab called About with the OpenCarOS logo and build tag.

**Comment by hawkeyexp** [comment]
Thx for the feedback.
The build tag will remove after csng has left pre-releases.
About the black header: some spece is needed for some labels etc and depending on wallpaper they are not really good readable. I will tune a but the opacity to reduce the hard break in upcoming release.

**Comment by pumpkintechlabs** [comment]
Thanks @hawkeyexp 
For the status labels like USB Connection etc is it possible to use a label with a white background and black text? If you put a background colour on the label it will be visible on any wallpaper and this eliminates the need of the top black bar altogether,

**Comment by hawkeyexp** [comment]
have a look on the next build - i think the opacity for the header will be a good compromise
