### ISSUE TITLE
[Tracking issue] Wiki

### ISSUE THREAD

**Issue by inspector71** [htruong/crankshaft#234]
Just thought I'd keep everyone informed of any wiki updates in a separate issue here. Might help to keep things syncronised or whatnot.

20190121: Updated [Settings Menu ](https://github.com/opencardev/crankshaft/wiki/Settings-Menu) for Alpha2
20190120: improved changelog in prep for Alpha2
20190120: Deleted draft SWC page
20181222: [Updated](https://github.com/opencardev/crankshaft/wiki/Home/_compare/b6b0f0e0688fed015bb70c4874ff48b929d1556f) home page (adding screenshot!)
20181020: Re-wrote [home page](https://github.com/opencardev/crankshaft/wiki)
20181019: Added steps specifying necessity for setting a password (`hotspot_psk=`) to [AAoWiFi page](https://github.com/opencardev/crankshaft/wiki/Android-Auto-Wifi) 
20181010: 3.5mm jack note
20181001: Customizing [tweaks](https://github.com/opencardev/crankshaft/wiki/Customizing-Crankshaft/_compare/be1d5ac0f815d07d03501e84dbdc63237146c15c...df8cdeea1be39bcaaaad1a78de510f797f435c67)
20180928: Settings Menu [updates](https://github.com/opencardev/crankshaft/wiki/Settings-Menu/_compare/a2be85fcadbf19822b18195eae73244dbd62380c...4c68af5b75dba4c6919ae953ad345ccfbb1dbf26)
20180927: [Changelog tweaks](https://github.com/opencardev/crankshaft/wiki/General-Changes---Changelog/_compare/35b1864be2bf76aa6057066fdd86f2b4d92c08cc...defc66d192ce1ff79f189dc3c323fa67ebb1828e)
20180927: External Storage - Added paragraph noting `/media/CSSTORAGE` is scanned for mp3s
20180927: [Hardware support tweaks](https://github.com/opencardev/crankshaft/wiki/Hardware-support/_compare/75fe68dad15ee655a79dce6c379b668176dd7499...2cfdda21a252ea649f74f92c38a3c8cdc9930c7d)
20180926: [Changelog tweaks](https://github.com/opencardev/crankshaft/wiki/General-Changes---Changelog/_compare/f568d495e66f29c32146ac6e141c55b7b3925b49...35b1864be2bf76aa6057066fdd86f2b4d92c08cc)
20180922: [Bluetooth](https://github.com/opencardev/crankshaft/wiki/Bluetooth) re-written
20180922: [Audio setup](https://github.com/opencardev/crankshaft/wiki/Audio-Setup) polish, partial re-write, update strings 
20180920: [External storage](https://github.com/opencardev/crankshaft/wiki/External-Storage/_compare/619a16ef5a617d40f0177a4c6225cb6f492f4505...c39be5db62b856a325e15ef1a438bb2d6bee0029#diff-5779c197636e13419baaf438dfa6a57b) largely re-written

**Comment by hawkeyexp** [comment]
Good idea - thx...

**Comment by DJFliX** [comment]
@inspector71 I was just told by @hawkeyexp that you are an active contributor to the wiki. I grouped and re-ordered the wiki menu entries but saw this issue and wanted to know if it makes sense to keep logging changes here. The last changes were logged about 3 months ago. If we don't keep logs of wiki changes here I guess this issue might as well be closed, right? :)

**Comment by inspector71** [comment]
Hi DJFliX.

I think it makes sense to have a place where we can discuss wiki editing as randomly editing risks chaos.

I don't know how we could have that discussion space. Reddit, GitHub issues ... none seem quite right.

I've been somewhat lazy in not updating this issue as my motivation has been tainted by the annoying limits of GitHub Wiki and people in the Reddit often failing to acknowledge @hawkeyexp's efforts and just whinging about bugs (in alpha level software!).

I suspect it might make more sense to move documentation away from the heavily limited GitHub Wiki software. Perhaps to getcrankshaft.com
