### ISSUE TITLE
Android auto dont want to start

### ISSUE THREAD

**Issue by krooozong** [htruong/crankshaft#237]
Hey,

i am new at this forum and have a problem with rasperry pi 3 connected to a 7 inch touchscreen.
I just want to use it in my car with android auto. 

My problem is that the android auto dont want to start, as in the tutorials that i saw. 
My rasperry and screen starts normally but  i get not the screen of android auto. Just the wallpaper menu and the settings. So my question is: What do i have to change that my android auto starts automatically ???

I attach some pictures to see what screen i get the whole time
System: 2018-09-14- crankshaft-ng-F6184EB

![img_20180923_200100](https://user-images.githubusercontent.com/43521879/45931265-f35a7e00-bf6b-11e8-8eef-236c40d28180.jpg)
![img_20180923_200108](https://user-images.githubusercontent.com/43521879/45931266-f35a7e00-bf6b-11e8-9845-42eef8448301.jpg)

**Comment by tehniemer** [comment]
It doesn't look like you have a phone connected.

**Comment by krooozong** [comment]
No i dont but is this the normal screen ? 
In some tutorials is the the screen of android auto. With the advice connecting the phone !
 
Like this 
![android auto](https://user-images.githubusercontent.com/43521879/45931418-4c2b1600-bf6e-11e8-9b6d-26ecaf5317a5.jpg)

Thx for comment

**Comment by hawkeyexp** [comment]
@krooozong - this is the new gui with csng (pre-releases) so all fine.
You have to connect your phone and android auto should launch - it's only a projection which is working with phone connected no standalone solution. If you android auto didn't launch have a look into the wiki and create a debuglog.

**Comment by krooozong** [comment]
okay thx. 

Thumps up

**Comment by hawkeyexp** [comment]
seems like the issue can be closed...
