### ISSUE TITLE
Request: Throw away wake-up touchscreen click

### ISSUE THREAD

**Issue by beanot** [htruong/crankshaft#239]
Nexus 6p on CS-NG Pre10 with official 7" touchscreen.

Currently screen goes blank on idle, and can be woken up by a click.
Problem is that the click gets processed, so no way to ensure that wakeup click won't result in unintended effect (e.g. switching audio track, changing nav, etc).
Any simple way to just throw away the click (after using it for wakeup of course), or perhaps on blanking change input mode so next click won't actually do anything beyond wakeup (e.g. have it act like hitting <SHIFT> key)?

**Comment by hawkeyexp** [comment]
Yes i know - something will be released for this with next builds - currently tap on top center there is no control item

**Comment by hawkeyexp** [comment]
Fix is done and will be available with next build. Was to late for pre11 sorry.

**Comment by beanot** [comment]
Thanks for quick response. Just installed pre11, looking forward to playing around in it tonight. Have a good weekend!

**Comment by hawkeyexp** [comment]
Thx, you too.
