### ISSUE TITLE
[CSNG] Automatic upgrade failure from pre10 to pre11

### ISSUE THREAD

**Issue by tehniemer** [htruong/crankshaft#243]
I went about the upgrade process as I have since automatic upgrading was implemented, but this time the screen went blank in the middle of the process and never came back. The card is now write protected and I cannot flash the image manually or even format the card.

**Comment by hawkeyexp** [comment]
sounds for me like youre card has died. Possible you can try to repartition the card if it fails it's clear and Ende oft life for the card. The flash process itselve is working fine and no changes was done.

**Comment by tehniemer** [comment]
Bummer, I've never had a card fail on me. It was only about a year old too.

**Comment by hawkeyexp** [comment]
it can happen every time - no software prob

**Comment by smartroad** [comment]
Not directly related to this but as a bit of moral support, I have a 128GB flash drive that died after only about a year and a half of use. Wasn't heavily used but still. Sometimes I think it is luck of the draw as to when a device will die.

**Comment by hawkeyexp** [comment]
Closing cause not software related.
