### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by dreamvictim** [htruong/crankshaft#245]
The offline MP3 player is amazing!!! But what would make Crankshaft even better would be a video player.. I understand the safety implications of having such a feature but manufacturers of car head units provide the ability to play video but only when the handbrake is applied. Is it possible for Crankshaft to provide the same? Perhaps only allowing video to play when the handbrake is applied connected via a GPIO pin?

**Comment by hawkeyexp** [comment]
Thx for feedback - some more improvements will step in next time to improve usability.
About video playback - sorry, but no. You are correct some manufacturers have this feature with the described lock to ensure nut using while driving but this are builtin system with hard locks. A lock via gpio etc is useless cause a jumper does the trick - good try :-)
I'm still at the position: a Headunit needs no video playback. The eyes have to be on the road and in most cases nav is open etc so player is invisible. I also know the arguments whily taking a brake from driving watching some vids etc. but sorry no work in this part of soft :-) Hope you can acdept this general
decision.
