### ISSUE TITLE
AudioInjector HAT is muted

### ISSUE THREAD

**Issue by ktrenx** [htruong/crankshaft#246]
I am getting no audio from my AudioInjector Stereo HAT in CS, I have tried pre8-pre11. I have added 'dtoverlay=audioinjector-wm8731-audio' to config.txt and CS pre-11 now sees the card in options.
In other OS installs I have to unmute 'Output Mixer Hifi' in alsamixer, but doing so in CS dev mode doesn't save through a reboot, even if I follow it with 'sudo alsactl store'.
A user on Reddit suggests that it may be a PulseAudio issue and recommended contacting AudioInjector. I have tried asking on the AudioInjector forum, but they have not posted my question in their forum.

**Comment by hawkeyexp** [comment]
- Please try first a non manual setup via settings cs-hw - select your dac and select save on exit and do a reboot. Try if output is working after this.
- Alsactl won't work cause it's a readonly filesystem in normal mode - use crankshaft audio alsactl save|restore instead which saves the alsastate to /boot/crankshaft/alsactl.state.
- An unmute command ist send to the card via autoapp_helper on start of openauto.
I know from another user his card is working. With latest builds.

**Comment by ktrenx** [comment]
I just tried a fresh install of pre-11, the only output available under Pulseaudio Input / Output Device is [bcm2835 ALSA] | alsa_output.platform-soc_audio.analog-stereo and nothing available under Input. No audio from the hat

**Comment by hawkeyexp** [comment]
create a debuglog from this install and add it.

**Comment by ktrenx** [comment]
[debug.zip](https://github.com/opencardev/crankshaft/files/2453267/debug.zip)

**Comment by hawkeyexp** [comment]
You have not done a correct setup as recommended via settings CS-HW - Possible forgot to set the flag save on exit ?

**Comment by ktrenx** [comment]
you are correct, absolutely an oversight on my part. Everything is working great now, thank you for your help

**Comment by hawkeyexp** [comment]
you're welcome
