### ISSUE TITLE
Non official screen turns blue in Screen off mode

### ISSUE THREAD

**Issue by dvg87** [htruong/crankshaft#248]
First of all thanks for all the hard work that you guys put in this fantastic project.

I use:
Samsung S8
Android 8.0.0
Pre11 
"Landzo" 7" screen

Everything works fine except that I use a non-official screen. When I use the Screen Off Timeout
the raspberry turns off the screen output after disconnecting the phone. 

But because it is a "Landzo" screen the backlight is not controlled by the raspberry but by a button on the screen pcb. So when the raspberry turns black the screen does not receive input. Therefore this screen turns blue with the message "no input". 

My question is, is it possible to have the Screen Off mode outputting a black colored screen instead of really turned off screen?

**Comment by hawkeyexp** [comment]
I'm sorry this is not possible - the wanted result is to bring the screen in powersave/off mode so a powermanagement signal is send and the the official screen brightness is set to 0% - this is the way most screens working fine with - if your screen has an osd which is shown nothing can be done - it's device dependend - but usually after some seconds the screen will also go to powersave. Outputting a black screen will keep screens on (backlight on) so nothing i will release. The only way you can think about is to release a custom replacement for the button on the screen which allows a remote control via the pi.
