### ISSUE TITLE
Archive Crankshaft Classic wiki?

### ISSUE THREAD

**Issue by inspector71** [htruong/crankshaft#249]
Do we think it's a reasonable time to archive or deprioritise the Crankshaft Classic wiki content? Seems a bit silly to have it as the first part of the wiki sidebar, at least.

https://github.com/opencardev/crankshaft/wiki

**Comment by ahoneybun** [comment]
A link to the site in question is always good to have in the bug report.

**Comment by hawkeyexp** [comment]
@inspector71 yes i think we can start to restructure the sidebar - i will add some more docs next time cause i think csng is stable enough and not longer so fast reworked as in the past.

**Comment by inspector71** [comment]
> 
> 
> @inspector71 yes i think we can start to restructure the sidebar - i will add some more docs next time cause i think csng is stable enough and not longer so fast reworked as in the past.

Sounds good @hawkeyexp. Perhaps you could create a new roadmap, or update the loose roadmap here

https://github.com/opencardev/crankshaft/wiki/Project-philosophy

Must admit, I guess I kinda got a little addicted to the momentum of CS progress. It would be helpful for me to know if that momentum is going to taper off somewhat.

**Comment by inspector71** [comment]
Looks like I just managed to flip the order of the _sidebar so NG is at the top. This seems more intuitive and reflective of the project's current order / status.

**Comment by htruong** [comment]
I totally agree with inspector71 :)
