### ISSUE TITLE
[CSNG12] Keep screen on while playing on built in player

### ISSUE THREAD

**Issue by smartroad** [htruong/crankshaft#251]
Is it possible to have the screen left on when playing music using the built in player? At the moment the screen goes blank after 2(ish) minutes.

**Comment by hawkeyexp** [comment]
I was thinking about in the past but didn't release it currently. I think the only clean way would be disabling screen off until player has nothing more to play and reenable screen off if playlist is stopped a while. If generally disabled while player is shown etc. will break the full feature. As temp solution you can disable screen off generally.

**Comment by smartroad** [comment]
Would it be possible to take what ever variable holds the "last pressed time" and constantly update that as long as the player is playing something? That way when it stops the timer would carry on normally. Not a particularly elegant solution but could be effective?

**Comment by hawkeyexp** [comment]
not possible directly cause the timer stuff is native released in the system. But we describe the same way.

**Comment by hawkeyexp** [comment]
done with next build
