### ISSUE TITLE
[CSNG12] Use same keyboard controls for built in music player as for AA

### ISSUE THREAD

**Issue by smartroad** [htruong/crankshaft#252]
I have setup 3 buttons on the GPIO and linked to the 3 buttons used to control AA's music playback (previous, next and play/pause - keys V/N/B). Is it possible to have the music player respond to those keyboard inputs as well?

**Comment by hawkeyexp** [comment]
Possible later - it needs some rework of the code inside openauto.

**Comment by hawkeyexp** [comment]
@smartroad I will try to implement something next time - would you be open to test it if included cause if have no buttons currently connected?

**Comment by smartroad** [comment]
Sure no problem 😁

**Comment by hawkeyexp** [comment]
Button controls implemented and available with next build.
