### ISSUE TITLE
Button for temporarily monitor turn off

### ISSUE THREAD

**Issue by LoganFanGer** [htruong/crankshaft#254]
Is it possible to create a tile on the start page with a command, that turns off the monitor temporarily? I run the system at staedy plus and  for short stops, this function would be great! 

THX for your good work! System works great since many weeks.

**Comment by hawkeyexp** [comment]
as possible way you can create a custom button and a backend script which toggles betwen screnn on/off.
The csmt can control the display - `crankshaft display on|off`

**Comment by LoganFanGer** [comment]
Thank you. I'll try my luck. But unfortunately I fail to create the config file. I also do not understand the manual "Custom Buttons". Do not get there......

**Comment by hawkeyexp** [comment]
wha'ts the problem ? You can als use the csmt (crankshaft command) to create a dummy file to edit it

**Comment by LoganFanGer** [comment]
I start in Dev-Mode and connect by Putty. Start Command "crankshaft buttons 1" shown in the "Custom Button description" to create a config file. 
Console says "Done" But neither in the folder crankshaft nor in crankshaft / custom a file appears for editing. What am I doing wrong?

![custom button](https://user-images.githubusercontent.com/37416102/47257425-e018d080-d48d-11e8-96b3-6d5db96db36c.JPG)

**Comment by LoganFanGer** [comment]
Argh...the "correct" command is "crankshaft buttons create 1". File "button_1" is now in folder /boot/crankshaft. 

A first success. Continue experimenting  ;-)

**Comment by LoganFanGer** [comment]
2 step. I create an orange Button with the label "Monitor OFF". Works fine.

Monitor OFF#/your/command#255,127,036#

![20181020_183500](https://user-images.githubusercontent.com/37416102/47258177-aa78e500-d497-11e8-89d1-0ee7ca079918.jpg)

But what is the correct syntax to implement "crankshaft display on|off" in command section? And whats the right path?

Using command ""crankshaft display off" in console works, but I can not integrate that.

**Comment by LoganFanGer** [comment]
3 step....lol

I create file in /boot/crankshaft/custom. Named "displayOFF" 
with the following content "crankshaft display off"

Content in button_1 is now:
Monitor OFF#/boot/crankshaft/custom/displayOFF#255,127,036#

and it works  ;-) By pressing the Button monitor switches OFF.

Last problem, how to toggle it ON ??? Any idea for the script?

**Comment by hawkeyexp** [comment]
You ned a simple if else condition - but as i noticed a start prob fro aa in another issue wait 1 or 2 days until the bugfix release will be available - i will extend the crankshaft command for you with a toggle.

**Comment by LoganFanGer** [comment]
Super, thank you!

**Comment by hawkeyexp** [comment]
The startup issues from pre13 which has stopped publishing is solved and a new release is on it's way - including a toggle command for you `crankshaft display toggle`
