### ISSUE TITLE
Display IP addresses under CS Base, System Info?

### ISSUE THREAD

**Issue by inspector71** [htruong/crankshaft#256]
Would it be possible to add the current IP address for ethernet, and / or WiFi, to the `Settings` app, `CS Base`, `System Information` section?

**Comment by hawkeyexp** [comment]
Yes this will come ... i has also thinked about adding it

**Comment by inspector71** [comment]
Cool, should help with connecting via SSH :)

**Comment by hawkeyexp** [comment]
With next build included also a reworked network handling.
