### ISSUE TITLE
[CSNG13] Not loading AA

### ISSUE THREAD

**Issue by smartroad** [htruong/crankshaft#257]
AA doesn't load when connecting to phone. Phone just asks to connect using USB (I guess as it see's the Pi as a computer and wants to connect as a drive?)

- What phone do you have?
Samsung A5
HTC A9

- What OS version?
8.1
7.1

- What crankshaft version?
NG13

- Steps to reproduce the bug, if you're planning to report a bug. Please indicate whether the bug is always repoducible.
Update from NG12
Connect phone after boot

- Please provide any further information that you might find helpful if available.
[debug.zip](https://github.com/opencardev/crankshaft/files/2498299/debug.zip)

- Starting with pre4: Boot into dev mode (can be selected in settings).
  Reproduce the possible bug. Create the debug logs by pushing the grey button on bottom of screen.
  Add the created file (/boot/debug.zip) to the issue.

  Warning: if you have configured wifi passwords they will be blanked by script during creation.
  We can't make absolutly sure you passwords are removed so do a personal check of the files inside the zip.

**Comment by hawkeyexp** [comment]
Seems to be correct - have to debug the reason - possible a part in the newer qt changes cause aa wifi works.

**Comment by hawkeyexp** [comment]
Problem solved - release on it's way...
