### ISSUE TITLE
USB mount ok but is empty

### ISSUE THREAD

**Issue by larusenanus** [htruong/crankshaft#259]
What phone do you have?
Huawei Mate 10
What OS version?
Android 8.1
What crankshaft version?
Crankshaft OpenCarOS NG Pre12 2018-10-24

I format my usb in FAT 32, call it CSSTORAGE and when I put it in rasperry the mount is OK, but, in player mp3 the USB dialog is empty and when I touch "Mount"  again  , the crankshaft crashed, somem help please?

**Comment by hawkeyexp** [comment]
The CSSTORAGE is excluded cause it's a default system part if present and mounted during boot. The mount dialog inside the player is designed to have a way to access usb storages with media content which are hot plugged. Generally place music files on the Folder Music on top of filesystem root and they will be linked and available in the player. Doc update will follow next time.

**Comment by hawkeyexp** [comment]
USB mounts reworked and now fully handled by system udev. No manual interaction needed anymore.
Coming with next build.
