### ISSUE TITLE
CSNG13 - boot logo covers menu when loaded

### ISSUE THREAD

**Issue by dreamvictim** [htruong/crankshaft#261]
Crankshaft boot logo stays on screen on top of menu when menu has loaded. See attached photo.

![img_20181027_162305404_hdr](https://user-images.githubusercontent.com/41390236/47606170-0b5c6c00-da08-11e8-8250-9038aed653d2.jpg)

**Comment by tehniemer** [comment]
I have the same issue with 13-1

**Comment by hawkeyexp** [comment]
Add a debuglog to get more info - never had this effect... but looks like splash is on top of openauto.

**Comment by dreamvictim** [comment]
[debug.zip](https://github.com/opencardev/crankshaft/files/2522157/debug.zip)

Debug attached. I have to click settings button and then cancel for the crankshaft logo to disappear.

**Comment by dreamvictim** [comment]
It's being caused by X11 mode. I've just tried EGL and it works as it should.

**Comment by hawkeyexp** [comment]
EGL is the default - also had this ide caused by x11 and tried on my testsystem and there it works fine - will check your debug

**Comment by hawkeyexp** [comment]
debug looks good - also the terminate command to plymouth is send

**Comment by hawkeyexp** [comment]
Try adding `sudo plymouth --hide-splash` inside /opt/crankshaft/service_openauto.sh before xinit and autoapp - the correct lines has as also a description like #Starts the autoapp...

**Comment by hawkeyexp** [comment]
does it fix your effect ? I can't reproduce it...

**Comment by dreamvictim** [comment]
I tried adding the line to service_openauto.sh but unfortunately it didn't work, also I noticed that once open auto had booted the line I added was removed. I'm running EGL now which works absolutely fine and looks better. I had noticed whilst running X11 some aspects were not central on the screen such as the MP3 covers.

**Comment by hawkeyexp** [comment]
If the line gets removed something must be wrong - there is no codepart which edits this file during boot. Are you sure you have edited the file in dev mode or switched the filesystem to rw and saved your edit correctly?
About alignment i will have a look...

**Comment by dreamvictim** [comment]
Like this?

        # Starts the Autoapp (OpenAuto) main program via x-server
		sudo plymouth --hide-splash
        xinit
    else
        # EGLFS - crankshaft "normal" mode

**Comment by dreamvictim** [comment]
Ok I re-did it in devmode. That worked, the screen goes black for a few secs now after the crankshaft logo. But I did get this error on the screen. (not sure if you can read it but I've attached a photo).

![img_20181028_215150175](https://user-images.githubusercontent.com/41390236/47622364-3c1dcd80-dafc-11e8-9e89-2d35b4a99782.jpg)

**Comment by hawkeyexp** [comment]
This looks like a demaged filesystem/sdcard

**Comment by dreamvictim** [comment]
Must be a coincidence then as it happened after I edited the file. I'll do a fresh install and see if it goes away.

**Comment by dreamvictim** [comment]
Ok, so I did a fresh install on the SD Card and everything appears to be working properly now. Apologies for wasting your time! If anything weird happens in the future I'll do a fresh install first before posting. If you could have a look at the screen not being central on X11 that would be great.. Thank you.

**Comment by hawkeyexp** [comment]
Can you take a pic of the wrong alignment - would be helpfull...

**Comment by dreamvictim** [comment]
First photo is EGL and aligned perfectly. Second photo is X11.
![img_20181028_215115318](https://user-images.githubusercontent.com/41390236/47714043-adac6780-dc33-11e8-9382-f6f7675d9c17.jpg)
![img_20181028_214907004](https://user-images.githubusercontent.com/41390236/47714069-c1f06480-dc33-11e8-80f0-bfb7a3c04763.jpg)

**Comment by hawkeyexp** [comment]
ah ok - only in x11 mode - thx
