### ISSUE TITLE
Mic works in Settings but not when AA is active

### ISSUE THREAD

**Issue by Dolneaz** [htruong/crankshaft#262]
- What phone do you have?
Xiaomi Mi A2 Lite

- What OS version?
Android 8.1

- What crankshaft version?
Pre 13-1

I switched from the build in Audio to a external Audio Card. The Output Works greate and the sound really improved but then i trigger a voice Command and the USB mic did not work. Testing it via playback in settings menu the mic worked just fine. 

If i use a USB mic and the build in Audio it works just fine. But If i use the USB mic and the USB External Sound Card it seems to work in settings but does not in AA projection.

**Comment by Grawa** [comment]
I have the same problem with galaxy s9+ but only in **wifi mode**, instead in usb mode it works perfectly

**Comment by hawkeyexp** [comment]
Also tried switching audio backend in settings ?

**Comment by Dolneaz** [comment]
Sry for the delay in my response. I was on vacation^^
If you mean switching between "rt audio" and "qt audio" that did not help ^^.
Also i discovered another stange problem. When i enter the settings menu and then exit it (no matter if hitting save or cancel) the pi wont recognize my phone anymore and AA does not start. After a restart everything works again. Also: Is it normal that when starting the Pi crankshaft get loaded then exits after some seconds, shows the console login and then starts the UI again ?

**Comment by hawkeyexp** [comment]
About mic try to add a debuglog please.

About the settings effect: i noticed this some days ago, too - have to diag why cause in the past i'm sure it was working fine.
About restart in x11: it's known - but no high prio in the past cause x11 is only last way to get system working with displays i don't like :-) - default usage is in egl. But currently preparing a build for first stable release which should be bugfree as possible so this effect will e also adressed.

**Comment by Dolneaz** [comment]
WOW :-) You are fast man 
How do i create a debug log ?  But i guess it wont show something since it works in settings. But i will try if i foudn out how. 
I can tell oyu that the settings effect was not present in Versioon pre8 since i used that a long time and had no issues with that one.
Reguarding the x11 crash. If it helps: the Hotspot is not present at first startup. After second startup it shows up on handy and in the crankshaft GUI.
Im only using x11 cause my handy has a notch and AA projection is bugged then bith black borders in top and bottom. I set up crankshaft in the way that margins remove that borders. Since buttons also get removed i installed a numpad into the car and remapped the keys to normal Open auto input keys XD and that only works in X11 .... I happy when Android pi rolls out for my phone and i can remove this dirty workaround....

**Comment by hawkeyexp** [comment]
You can create it in two ways: enable debug mode in settings and reboot - you will get a button to create.
Alternate connect via ssh and run `crankshaft debuglog` from shell.
About hotspot: there are some changes since pre 13-1 which should fix all effects from the past and hotspot can instant activated via settings without reboot - also a switch back to client mode will be available.
Interesting effect with the notch. Possible Google will address it - would be interesting if this effect also happens on commercial headunits...

Have you used all builds from pre8 to pre13-1 or direct stepped forward? Would be helpfull to reduce the possible parts which causes the thing with the settings...

**Comment by Dolneaz** [comment]
The issue is confirmed on Real headunits and is a knows error for phones with noth. Just google Android auto Noth problem and there will be a ton ^^ Its not googles fault. They never oficially supported notches until android P so why shoudl they. The Producers of the phones are responsible for the mess ^^ And Xiaomi will not fix it when andorid pi will be available on the relevant phones soon. (Planned for my phone is Q1 of 2019)
No sry. i directly switched to the 13.1. i only upgrad eif there is a feature that i definitly want. After the media player is there the only reason left are bug fixes for really important stuff and the working bluetooth for phone calls ^^ Cause atm even with the adapter that supports hands free it didnt work :-(

**Comment by Dolneaz** [comment]
I will try to spare some time at weekend to get the Error logs :-)

**Comment by hawkeyexp** [comment]
I had a look to x11 restart and seems i had luck and could solve it.
Try change to `TTYVHangup=no` in `/lib/systemd/system/getty@.service` and do a `sudo systemctl daemon-reload` after edit - this should fix the effect. Commit is up for next build.

**Comment by Dolneaz** [comment]
Thanks for looking at that :-) Is fixing it now worth it for me? Cause i have to change up some stuff to plug in a keyboard with my current setup ? Cause when the new version is out i would do that too to get all the other stuff :-) i guess i have  to get a usb cable to be able to easily plug in usb devices that are not the phone ^^

**Comment by hawkeyexp** [comment]
Ok no prob - this will be included with next build cause it was a general behaviour - i think next week a new release will be published.

**Comment by hawkeyexp** [comment]
About x11 start behaviour it is fixed in pre14 and about sound it's working without probs for me - can we close this issue ?

**Comment by Dolneaz** [comment]
Sry. I did not had the time to test with new veraion. Last time i had some time i tried to get pre 14 to work but android auto refuses to start on my phone. And sometimes it geta completely broken. When i have some time i will try again and do a screenshot. It showed the bash and in front of the bas i was able to see some rests of the open auto gui like the top bar with the clock.I will try to test again soon. But you can close this issue i guess. If i get it to work again i will test and then create a new. And if not there will be the need for a seperate issue anyway. Debug mode is off and i did no changes to the phone since last version. And bac then with pre13 it worked

**Comment by hawkeyexp** [comment]
ok - closing.
