### ISSUE TITLE
Connect to wifi network in dev mode

### ISSUE THREAD

**Issue by smartroad** [htruong/crankshaft#264]
I can't figure out how I can get my install to connect to my home wifi when I am running the unit in dev mode. I've been wanting to SSH into it to simplifiy writing a Python script for changing day/night mode.

Tried raspi-config, but it doesn't work and changing wpa-supplicant.conf manually doesn't stick when the unit reboots.

**Comment by hawkeyexp** [comment]
Enter your wifi credentials in /boot/crankshaft/crankshaft_env.sh - wpa_supplicant.conf is created from this values on boot. With next build a preconfigured wpa_supplicant.conf is also possible.

**Comment by hawkeyexp** [comment]
Closing - no more feedback...
