### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by nizzaluca** [htruong/crankshaft#267]
- Nexus 5X on Android 8.1
- Raspberry Pi 3 Model B 
- Official Raspberry 7" touchscreen

when connect usb cable, on the Nexus 5X I see android auto, android auto propose to start, I touch and then return home.

_Originally posted by @emacor79 in https://github.com/opencardev/crankshaft/issues/2#issuecomment-419651634_

**Comment by hawkeyexp** [comment]
Please create a debuglog after connecting device and the effect happens which could pssible show a reason why - generally there should be no prob...
