### ISSUE TITLE
Possibility to add support for Seeed Voicecard while exposing AlsaMixer to end users.

### ISSUE THREAD

**Issue by cydia2020** [htruong/crankshaft#268]
Seeed voicecard is a range of mic arrays that works with the Raspberry Pi for voice recognition, they're cheap and they work fairly well as seen from the testings done on my own hardware, the mic is reasonably clear; however it is not currently implemented in Crankshaft, the steps of implementing is detailed below

https://github.com/respeaker/seeed-voicecard
http://wiki.seeedstudio.com/ReSpeaker_4_Mic_Array_for_Raspberry_Pi/

----------------------------------------------------------------------------

One other thing, some of the models such as the 2-mic hat has an audio jack output, the quality of the output is better than the integrated jack. Nevertheless, the output volume is being controlled by "Headphone" option within alsamixer, but crankshaft does have a tendency of not reading alsactl.state nor asound.state while booting, making the volume settings not persisting after a reboot.

However this should be an easy fix by just booting with the command
`alsactl --file /boot/crankshaft/alsactl.state restore`

The headphone state needs to be save prior nevertheless with
`alsactl --file /boot/crankshaft/alsactl.state store`

----------------------------------------------------------------------------
AlsaMixer provides a range of values to be controlled by the user for these particular arrays, these options are not accessible within crankshaft, it should be possible by exposing AlsaMixer to the UI, letting the users thinker with the values.

**Comment by hawkeyexp** [comment]
Alsa is only the low level access to the hardware. This is not useable in cs cause alsa allows only access by one connection and blocks other. This won't allow for example bluetooth stuff cause this must be fully handled by pulseaudio which is the default audio server.
Alsa state is stored and restored during clean shutdown and start and additional it is available via csmt for manual usage. I'm sure pulseaudio can handle this device if you have a deeper look into handling audio devices with pulseaudio.

**Comment by cydia2020** [comment]
Okay, thanks, I'll give it a shot.
