### ISSUE TITLE
[WANTED] C++ / Qt5 Dev

### ISSUE THREAD

**Issue by hawkeyexp** [htruong/crankshaft#270]
Hi@all,

is there any dev which would be open to help fixing some code related problems?

**Comment by DJFliX** [comment]
@hawkeyexp I have no experience with Qt5 but I *might* be able to help you with the CPP stuff (it depends on the complexity of course).

**Comment by hawkeyexp** [comment]
Thx for feedback :-) I think help is always usefull - i started at zero level :-)

**Comment by hawkeyexp** [comment]
@DJFliX how we can stay in contact ?

**Comment by DJFliX** [comment]
GitHub username @gmail.com is the easiest. I can give you other means of contacting me there.
