### ISSUE TITLE
Pre14 - Change "Equilizer background"

### ISSUE THREAD

**Issue by LoganFanGer** [htruong/crankshaft#271]
I want to modify the "Equilizer background for media player" picture. 
The pic is nice&cool, but i want to change some colours. What's the name of the file and where do I find it, please. I'm looking for a *.png file, but can only find the standard wallpapers.

**Comment by hawkeyexp** [comment]
Currently it is hardcoded inside the openauto app. I forget to make it external like the backgrounds. It will be relased with next build.

**Comment by LoganFanGer** [comment]
Thank you for the fast answer. Ok, waiting is no problem. 
Now, I see the Pre15 ... there is enough to test ;-) 
Thanks for your good work!

**Comment by hawkeyexp** [comment]
l'lI keep the issue open to not forget it :-)
