### ISSUE TITLE
Pulse audio warn in terminal when devmode enabled

### ISSUE THREAD

**Issue by WeredPerson** [htruong/crankshaft#276]
I have installed E9028A9 on a raspberry pi 3 B with the 7 inch offical touchscreen display, when entering dev mode and rebooting to try and use the terminal it is flooded with the message below which even overwrites vim and nano making the terminal completly useless. 

[ warn ] *************************************************************
[ warn ] Pulseaudio has detected 
[ warn ] Add an audio output device!
[ warn ] *************************************************************

**Comment by hawkeyexp** [comment]
switch back to Pre14 until next build is available - with new build it is fixed.
