### ISSUE TITLE
Pre16 - black bars on the sides of the screen in Android Auto environment

### ISSUE THREAD

**Issue by dvg87** [htruong/crankshaft#279]
I installed Pre16 yesterday. The Crankshaft environment still works fine.
But when I connect the phone and switch to the Android Auto environment it does not cover the whole screen. The screen shows black bars on the sides. Did I miss a setting?

**Comment by hawkeyexp** [comment]
Adjust screen dpi in settings until it fit's to screen

**Comment by 29axe** [comment]
@hawkeyexp Thanks for the tip. 126 dpi did the trick for me on official raspberry touch screen.

**Comment by dvg87** [comment]
Sorry for the late reaction but this also worked for me.

Thank you!
