### ISSUE TITLE
gpio2kbd.cfg and volume

### ISSUE THREAD

**Issue by gcharlie** [htruong/crankshaft#282]
Are Volume controls via gpio working in the latest NG releases? I can seem to get the pins assigned via the gpio2kbd.cfg for volume and brightness to have any effect. The gpio pins assigned via the settings menu do seem to work though. Is this function deprecated or am I missing something?

**Comment by hawkeyexp** [comment]
will check it the next days...

**Comment by LoganFanGer** [comment]
In Pre-16 that works for me without problems. Do you have the correct syntax in gpio2kbd.cfg? It looks like that for me! So, in AA, the volume and titles Next / Previous works fine. In the CS-NG media player only volume works.

![gpio2kbd](https://user-images.githubusercontent.com/37416102/50603936-9dc43480-0ebd-11e9-8918-971e9080266b.png)

**Comment by gcharlie** [comment]
Yeah I'm on the same version, same syntax. But I've been testing it just on the home screen. When I go to change the volume via the gpio pins, theres no change reflected on the volume bar along the bottom of the screen.

**Comment by hawkeyexp** [comment]
@gcharlie that's currently normal - changes done outside openauto won't be reflected to the gui.

**Comment by gcharlie** [comment]
Ah your right, it is working. That, seem kinda confusing though, especially since the bar on the home screen is the only visual indicator for the volume.

**Comment by Elmardus** [comment]
I am having the same problem. I use the default gpio2kbd.cfg and a Hifiberry DAC. Changing the volume with the slider on the crankshaft homescreen works, but I cannot change the volume using the gpio.

**Comment by hawkeyexp** [comment]
next time i will do some checks if it is possible to read it from inside openauto.
But i will close now the issue cause it was no real fail only a missing gui feedback.
