### ISSUE TITLE
Bluetooth not appearing on latest NG release

### ISSUE THREAD

**Issue by jamesb2147** [htruong/crankshaft#283]
Crankshaft-NG Pre(?) 16
Phone is a Unihertz Atom running Android 8.1

Fresh install with fresh hardware (RPi3). I'm not trying to use any adapters at this point, so this would be with the built-in Bluetooth. I'm aware of the upstream limitations that have been attributed to the chip vendor's firmware, so I don't expect calling to work or anything else requiring HFP. With all that said, I'm surprised that I cannot see Crankshaft-NG after boot (well within 120s), even though I've enabled the setting (should this be updated in the Wiki, BTW?). I go to scan for the device on my phone and cannot see it. I have joined other devices before without issue, including 4 cars, so I'm fairly confident in the Bluetooth stack on my phone in this case.

Steps to reproduce:
Install fresh Pre16 release on formatted SD card with Etcher (or dd or w/e; I used Etcher on Windows)
Boot Pre16 with official touchscreen
Go to settings and enable bluetooth for 120s on boot
Allow settings to save
Reboot
Search on phone for Crankshaft-NG (per Wiki)

Let me know if you have any questions or can't reproduce... I'll try to pull a debug file shortly.

**Comment by jamesb2147** [comment]
Just figured this out... looks like the Bluetooth adapter in settings is set to None by default. Should that be set to built-in by default, or should the Wiki be updated to reflect that the Bluetooth adapter setting must also be modified for it to work?

**Comment by hawkeyexp** [comment]
By default bt is disabled. this was included to prevent from double bluetooth devices if the user only put in a bt dongle and is wondering why something goes wrong.

@inspector71 Can you please add a hint?

**Comment by jamesb2147** [comment]
Added a step to the wiki to check device settings. Feel free to revise as necessary, but I'll go ahead and close this issue.
