### ISSUE TITLE
 some suggestions

### ISSUE THREAD

**Issue by x-tian71** [htruong/crankshaft#287]
HI
It's a fantastic job

I have some suggestions

GPIO 3 becomes fixed power on / off (soft) input pin

One of the GPIO becomes high when the device is on and low when it is safe to remove the power supply after power off so you can control a relay to among other external devices

I think there is a bug, regard to ignition I cannot make it work in any way

Raspberry pi3b+ & Crankshaft Pre16 2018-12-21

**Comment by Maju3** [comment]
You can use the 5V from one of the rpi usb port to control a relay.

The usb ports have power when the rpi is ON.

When the rpi is OFF (save to remove power) then the usb port powers off.

**Comment by Maju3** [comment]
https://drive.google.com/file/d/1YAe3UDfjVD3W1AVCY9gy8UkTauc6m6_E/view

**Comment by x-tian71** [comment]
THX - I hadn't thought about that.
But I thought it would be nice with a GPIO pin instead, :-) but would use the USB solution for now.
I use an Arduino Nano and a shady diy software to control my Rpi, amplifier and monitor :-)

**Comment by Maju3** [comment]
https://wiki.52pi.com/images/c/ca/1.How_to_use_1_GPIO_Pin_to_drive_RaspberryPi_Power-on-off-status_light.pdf

**Comment by Maju3** [comment]
You can use
Dtoverlay=gpio-poweroff

This will set a gpio pin LOW when the rpi is in shutdown.
And set the gpio pin HIGH when rpi is running

**Comment by Onigbagb** [comment]
I'm using f1xpl's BWS CAR PS power supply:
https://bluewavestudio.io/index.php/bluewave-shop/power-supply/bws-car-ps-v1-usb-detail

In Raspbian this script shuts down the system when ignition is turned off:
https://www.bluewavestudio.io/resources/bws-ps-installer.tar

Maybe we can integrate this, so we just use one GPIO pin for booting and shutting down the pi.

**Comment by LoganFanGer** [comment]
@Maju3
Have you test it under CSNG? Is it really working?

It runs perfectly on my Pi Zero with Raspbian. On CS not! Led is ON after shutdown, not wen running. I change  Low to High, but no effect. Any idea?

**Comment by Maju3** [comment]
@LoganFanGer 
I have NOT tested it sorry
I just use a 5V relay triggered by the RPI usb port so I do not Need a gpio pin as "save to remove power indicator"

**Comment by LoganFanGer** [comment]
Ok. Thanks. I will try again....

**Comment by viperidae** [comment]
I did a little testing using GPIO 3 to wake from HALT state on a Raspberry Pi 3 when you run the poweroff command.
Power usage went from running and idle at 5.2V, 390mA, down to 150mA in HALT state, where the VideoCore code is waiting for GPIO3 to be pulled low.
That's not really an acceptable power-off power consumption.

Additionally, GPIO3 is shared with the I2C port so it complicates connecting touch screens, rtc's, etc.

My plan is currently to use a relay and a few diodes that turns on when the car turns on and can be kept on by the Raspberry Pi via another GPIO.

**Comment by dpnkrg** [comment]
> @Maju3
> Have you test it under CSNG? Is it really working?
> 
> It runs perfectly on my Pi Zero with Raspbian. On CS not! Led is ON after shutdown, not wen running. I change Low to High, but no effect. Any idea?

Can you tell me the steps, to run this on  Pi Zero W ?

**Comment by LoganFanGer** [comment]
I am using the instructions that maju3 has posted (see #5)

https://wiki.52pi.com/images/c/ca/1.How_to_use_1_GPIO_Pin_to_drive_RaspberryPi_Power-on-off-status_light.pdf

Look at the instructions and connect a LED and a resistor to GPIO26. Then edit the file config.txt. Add the entry there:
dtoverlay = GPIO poweroff gpiopin = 26, active_low

Then restart with:

sudo sync
sudo init 0


Thats all....good luck ;-)

Make sure the latest Raspbian is installed, then the necessary package "wiringPi" is definitely installed!
