### ISSUE TITLE
Use phonescreen as input instead of touchscreen.

### ISSUE THREAD

**Issue by Bishamon1987** [htruong/crankshaft#289]
Hello,
I have a Motorola Moto 5 and Raspberry Pi 3B+, I use the latest crankshaft.

When I connect my phone with USB it works like a charm. But I want to use my stock touchscreen of my Chevy Volt. I am still figuring out how to use the touchscreen part with a HID controller. But in the mean time I want to use my phonescreen as input but see the video output off Android auto on the Chevy screen.
How can I do this?

**Comment by hawkeyexp** [comment]
Not supported sorry. Tochcontroller which works as hid should work fine for your project.
