### ISSUE TITLE
Android auto force landscape

### ISSUE THREAD

**Issue by Bishamon1987** [htruong/crankshaft#296]
Hey,
I don't know if this is possible on the pi side to force landscape mode while in Android auto?
For some reason my phone only want to show Android Auto in portait mode while connected to the pi. Turning the phone to get it in landscape doesn't work.
Thanks!

**Comment by hawkeyexp** [comment]
i think you are talking about the black lock screen right ? That's normal.

**Comment by Bishamon1987** [comment]
Yes on my phone it's the black screen but on my raspi screen it's also on
portrait mode. And I want to change that to landscape.

Op za 26 jan. 2019 09:33 schreef hawkeyexp <notifications@github.com:

**Comment by tsukisan** [comment]
You are seeing the lock screen in portrait mode on the raspberry pi screen running cs/aa?

The lock screen should only appear on the phone screen when running aa. Can you detail your setup a little more?

**Comment by Bishamon1987** [comment]
I'll make some pictures tonight when I'm home again.

Op za 26 jan. 2019 11:27 schreef tsukisan <notifications@github.com:

**Comment by Bishamon1987** [comment]
I do see the Android auto on my raspi screen so I can see the main screen of Android auto and navigation etc. But it's in portrait mode.

**Comment by hawkeyexp** [comment]
adjust dpi to 140 inside cs settings if you are using a rpi display - depending on res more...

**Comment by Bishamon1987** [comment]
I'll true it, but wondering this have effect on the crankshaft menu also?

Op za 26 jan. 2019 15:04 schreef hawkeyexp <notifications@github.com:

**Comment by hawkeyexp** [comment]
it's only for android auto projection

**Comment by hawkeyexp** [comment]
No response for longer time - >closing.
