### ISSUE TITLE
Change boot/Config file in settings?

### ISSUE THREAD

**Issue by Bishamon1987** [htruong/crankshaft#297]
It might be nice to be able to change the offset in the configs file within the crankshaft settings screen.

**Comment by hawkeyexp** [comment]
Please be more precise for issues

**Comment by Bishamon1987** [comment]
For some reason the DPI settings didn't save. So I reinstalled crankshaft
and now it works great.

Sorry for me being unclear with explaining the problem.

Op za 26 jan. 2019 19:57 schreef hawkeyexp <notifications@github.com:

**Comment by hawkeyexp** [comment]
no prob - closing...
