### ISSUE TITLE
question: Is it possible to use USB as video in (Rearcam)?

### ISSUE THREAD

**Issue by Bishamon1987** [htruong/crankshaft#300]
Is it possible to use USB as video in for something like a rearcam?
And if so, is it possible to auto detect when the cam is on and show the vid feed instead of android auto?

I want to use a rear (parking) cam with a composite (yellow) connector and put a video grabber (composite to USB) between the cam and the pi. 
Then I connect the power for the cam to a special socket for a rearcam (giving only power when rearing)
Then I want the cam to automaticly register its signal and go to rearcam view.
Is this possible, if so how?

**Comment by hawkeyexp** [comment]
i think it's a crossover between request and release - alpha-3 includes usb rearcam support :-)
It's tested with common usb webcam and working - you only need to enable it in settings -> cs-hw). I have no videograbber so this part is untested but if it creates a video device like /dev/video0 it should work.

**Comment by Bishamon1987** [comment]
I just tried to use my old Microsoft webcam. But it doesn't seem to work. I have these settings.
In CS HW 
Rpi-cam enabled fps 24 rot 0 res 720 no flip AWB and exp Auto
Usb-cam enable ltime 300 cnt 3 auto record disabled.

Where can I find this USB life video footage?
If I disabled rpi-cam I don't see the button on home screen.
So how does it work?

**Comment by hawkeyexp** [comment]
USB cam is only useable as rearcam. It is triggered via gpio which must be configured in settings.

I'll add a cam test option to csmt tomorrow.

**Comment by hawkeyexp** [comment]
i forgot cause i was tired - there is a way to use:

`crankshaft rearcam show | hide`

**Comment by Bishamon1987** [comment]
Where do I put this?


Op do 31 jan. 2019 11:09 schreef hawkeyexp <notifications@github.com:

**Comment by Bishamon1987** [comment]
Yesterday I upgraded to the latest release. But I don't see the CS MT tab in the settings menu. Or do I miss something?

**Comment by Bishamon1987** [comment]
Sorry I'm a noob with raspi's. But I found out about entering the pi with SSH.
Using Raspberry Pi 3+, now using my tv screen and mouse to set everything up. But after that I will put it in my Chevy Volt (I have to figure out how to 'high jack' the touchscreen input first).
But for some reason the `crankshaft rearcam show` command only gives a black screen. 
I can see the cam light turn on for a second when booting the pi. But it stays off the rest of the time.
On my other Raspberry Pi 2 B I run Octoprint (for 3d-printing), the cam does work there. So I guess the problem isn't that the cam is not recognized right?
So is there anything I can do to fix it or only try different cam?

**Comment by hawkeyexp** [comment]
Sorry for late response - but curently real live takes more time.
Please create a debuglog after you have tried to trigger the rearcam. You can use the button in settings -> cs env to create it. I need to know what happens in your system to debug what fails...

**Comment by Bishamon1987** [comment]
Hereby I send you the debug zip.
https://www.dropbox.com/s/jmbcpg0ckwo73h6/debug.zip?dl=0

**Comment by viperidae** [comment]
I also have a blank screen when using "crankshaft rearcam show". I'm using a Playstation Eye for the usb camera.
I too have used this camera with Octoprint too. No issues there.
[debug.zip](https://github.com/opencardev/crankshaft/files/2848710/debug.zip)

I've tried it in X11 and EGL mode too, neither worked.

**Comment by meekys** [comment]
For cam related issues, it might be worth getting the output from `v4l2-ctl --all`
The Pixel Format is probably the most important, if cam_overlay is being used, as it currently only supports YUYV. (YUVY pending feedback/confirmation from someone with the correct hardware)
JPEG/MJPG support is also being investigated

**Comment by enriquedelpino** [comment]
> Sorry I'm a noob with raspi's. But I found out about entering the pi with SSH.
> Using Raspberry Pi 3+, now using my tv screen and mouse to set everything up. But after that I will put it in my Chevy Volt (I have to figure out how to 'high jack' the touchscreen input first).
> But for some reason the `crankshaft rearcam show` command only gives a black screen.
> I can see the cam light turn on for a second when booting the pi. But it stays off the rest of the time.
> On my other Raspberry Pi 2 B I run Octoprint (for 3d-printing), the cam does work there. So I guess the problem isn't that the cam is not recognized right?
> So is there anything I can do to fix it or only try different cam?

I just noticed I am running the same setup as you are (Rpi 3B+ and Microsoft Life-Cam 3000), and I am getting exactly the same symptoms. When I execute `crankshaft rearcam show` I just get a blank screen, but I can see on the console that I'm getting an error on the underlying process (cam_overlay). Can you check if you get something like this?

```
pi@CRANKSHAFT-NG:/opt/crankshaft/cam_overlay $ ./cam_overlay.bin 
Opened device '/dev/video0'
Dimensions: 640 x 480 Pixel Format: YUYV
VIDIOC_REQBUFS error 12, Cannot allocate memory
```

I might as well give it a go on my RPi 2B and see if it does any difference

**Comment by ghost** [comment]
I can't use the USB Webcam, too. If got the Microsoft HD 3000 with a Pi 3b+. If I try to show the camera I'll get the following error: Insufficient buffer memory on /dev/video0. Do you need any logs?

**Comment by enriquedelpino** [comment]
Hi Stephan, 

I believe the issue is to do with cam_overlay, the program that displays the camera on the screen, rather than with crankshaft itself. I started a thread on the cam_overlay project, but I'm still waiting for an answer by meekys. You might want to check out that thread and see if there is finally a solution happening there:

[https://github.com/meekys/cam_overlay](url)

> I can't use the USB Webcam, too. If got the Microsoft HD 3000 with a Pi 3b+. If I try to show the camera I'll get the following error: Insufficient buffer memory on /dev/video0. Do you need any logs?

**Comment by Blackei** [comment]
Hi,
I have the Same Problem with the Blackscreen and the USB Camera

**Comment by Bishamon1987** [comment]
I have 3 different videograbbers and 1 webcam. They all seem to work out of
the box.
If you have issues with a black screen it might be that the software doesnt
recognize the camera as a video input.
You can check the /dev file if the video00 or video01 exists.

Check this list if its supported
https://elinux.org/RPi_USB_Webcams

With video grabbers its chip is important and the output format (yuvy,
mpeg, etc)

Op do 3 sep. 2020 18:58 schreef Blackei <notifications@github.com>:

**Comment by meekys** [comment]
There's a new branch (cpp) of cam_overlay that should support the mjpg/jpeg format, as well as plain yuyv.
Crankshaft may need to be updated to use this new branch. It is not the default branch as there have been some command line parameter changes, which break backwards compatibility.

Additionally, for people that are having issues with a black screen, it may be worth listing the output of
`v4l2-ctl --list-formats` as this should (hopefully) list the format(s) that the camera supports

**Comment by paull-oh** [comment]
Hey guys,

I have flashed Crankshaft OS (2021-02-09-crankshaft-ng-d5fffdd.zip
) onto my RaspberryPi 3B+ and it is working fine. I am now trying to implement a backup camera. I am using a raspberrypi official camera and have enabled it in CS-HW. When I run **crankshaft rearcam show** it just shown a blank screen on the rapsberrypi touch screen that I'm using. Do you know of a possible solution to this?

Thanks,
Toshi

**Comment by Compizfox** [comment]
I have the same issue here. I have a USB video capture stick that uses YUYV:

```
Format Video Capture:
        Width/Height      : 720/480
        Pixel Format      : 'YUYV' (YUYV 4:2:2)
```

Unfortunately, I'm just getting a black screen.

When manually running `crankshaft rearcam show` or running `cam_overlay.bin`, I get the following error:

```
Opened device '/dev/video0'
Dimensions: 720 x 480 Pixel Format: YUYV
* failed to add service - already in use?
```

I'm not sure what this means exactly, but from some Googling it looks like it's an OpenGL issue with cam_overlay.

I'm using a RPi 3A+, if that matters.

Any ideas?

EDIT:

It turned out to be a problem with hardware-accelerated OpenGL in cam_overlay. Everything works after removing `dtoverlay=vc4-fkms-v3d` from `config.txt`.

**Comment by Ramortada** [comment]
Is the issue with cam_overlay resolved ? Can we use video grabbers to show a camera signal ?
