### ISSUE TITLE
Saving a Bit of Power

### ISSUE THREAD

**Issue by EveAeternam** [htruong/crankshaft#31]
If you disable the onboard LEDs, you can lower the Pi's consumption by 30mA, which might make a difference for some (and those LEDs are not visible behind the dash anyways). Some power specs [here](https://www.pidramble.com/wiki/benchmarks/power-consumption).

**Comment by htruong** [comment]
Thanks for the suggestion. I will try to do it in the next releases or so.

**Comment by htruong** [comment]
Done! Implemented as in 0.2.0.
