### ISSUE TITLE
TSL2561 LightSensor

### ISSUE THREAD

**Issue by SergioMuinhos** [htruong/crankshaft#311]
- What phone do you have?
OnePlus 6T
- What OS version?
Android 9
- What crankshaft version?
 The last 

Hello, I bought the TSL2561 sensor and I have to solder and I do not know where to plug the pins. Can you help me?
 I bought this lightsensor and the pins where it is connected are occupied by an RTC and the screen itself, Any solution? Thanks

  Warning: if you have configured wifi passwords they will be blanked by script during creation.
  We can't make absolutly sure you passwords are removed so do a personal check of the files inside the zip.

**Comment by SergioMuinhos** [comment]
Hello, I bought this lightsensor and the pins where it is connected are occupied by an RTC and the screen itself, Any solution? Thanks

**Comment by LoganFanGer** [comment]
Both, the light sensor and the RTC communicate via the I2C bus. This can serve several devices at the same time. Although I have no light sensor, but I have tinkered for another application an adapter to connect two I2C-devices to the pins 1,3,5,7,9. Alternatively, you can solder something out of the Dupont cables. 

![bus-adapter](https://user-images.githubusercontent.com/37416102/53115522-b7413e80-3546-11e9-85d3-fdeeca94c99e.jpg)

The Screen also?! Thats not right. Normally its connected to PIN 2 or 4 for 5V and PIN 6 for GND!
![ds3231](https://user-images.githubusercontent.com/37416102/53116002-e310f400-3547-11e9-8c84-5c52ee280f7b.jpg)

**Comment by SergioMuinhos** [comment]
Where you have purchased all the components? or how could I do it?
Thanks for answering.

**Comment by hawkeyexp** [comment]
I2C is a bus system so you can connect multiple devices to it. Possible you need to solder a custom solution if you have parts with presoldered connectors.
The needed pins are documeted here:
https://github.com/opencardev/crankshaft/wiki/Brightness-Sensor
Please move discussions about howto solder etc to reddit. Thx.
