### ISSUE TITLE
Which small waterproof usb camara to use?

### ISSUE THREAD

**Issue by Bishamon1987** [htruong/crankshaft#313]
This is not an issue, but a question.
What rear view camera's do you guys use. 
I bought one with composite connection which is pretty hard do get working because of an extra usb device called video grabber, drivers seem not to work that great.

So I'm searching for a camera which is waterproof, small and has USB connection.

**Comment by hawkeyexp** [comment]
Please move questions like this to reddit where more users will notice it to give you hints. Thx.
Currently i think you have to create a small case for a cam to ensure no water will step into the cam.
