### ISSUE TITLE
Include drivers for video grabber for rear cam?

### ISSUE THREAD

**Issue by Bishamon1987** [htruong/crankshaft#314]
Is it possible for the developers to include some drivers for video grabbers like the UTV007 (Fushicai)?
It would allow people to use dedicated rearview cams that are waterproof (they always have composite output)

[Drivers for Video grabber for raspi](http://raspberry-at-home.com/video-grabber-for-raspberry-pi/)

**Comment by LoganFanGer** [comment]
An videograbber with UTV007 chipset works already without problems. There are no drivers required. With me that works flawlessly. Please note that the alternative chipset STK1160 does not work! 

Connect the Grabber via USB to your Pi, install your cam, go into the settings menu and activate the USB Rearcam setting. Thats all. Note that the picture of the camera comes only if you have configured a corresponding button on the Pi. I use an additional 12V relay, connected in parallel to the reversing light, to close the contact.

**Comment by cnckw** [comment]
What's up?

On Feb 26, 2019 12:43 PM, LoganFanGer <notifications@github.com> wrote:

An videograbber with UTV007 chipset works already without problems. There are no drivers required. With me that works flawlessly. Please note that the alternative chipset STK1160 does not work!

Connect the Grabber via USB to your Pi, install your cam, go into the settings menu and activate the USB Rearcam setting. Thats all. Note that the picture of the camera comes only if you have configured a corresponding button on the Pi. I use an additional 12V relay, connected in parallel to the reversing light, to close the contact.

**Comment by Bishamon1987** [comment]
Thanks man, just bought a video grabber with the utv007 chipset. SO tomorrow i’ll know. 
But I can use the rear cam gpio right?

**Comment by Bishamon1987** [comment]
So I received my video grabber with chipset UTV007 today. I plugged it in and tried via SSH `crankshaft rearcam show` and it worked! There is no big latency, maybe something like 200ms max.

**Comment by hawkeyexp** [comment]
including drivers won't be happen - if you need such special compiled drivers you need to compile it yourselve for the current kernel and add it possible via a custom script.  I recommend hardware which run's out of the box like the utv007 which was tested with @LoganFanGer ;-)
I think i can close this issue cause your last entry was a success report :-)
