### ISSUE TITLE
Screenshot

### ISSUE THREAD

**Issue by Bishamon1987** [htruong/crankshaft#321]
Hey,
The crankshaft screenshot command is a nice feature. But for some reason it doesn't capture the rearcam view when it's enabled. I get a black screenshot.
Is it possible to fix this?

**Comment by meekys** [comment]
If crankshaft is using cam_overlay, probably not. The rearcam image is decoded and shown in a GPU overlay.
I suspect you'd have a similar issue trying to take a screenshot of Android Auto itself too, as I believe this does a similar thing.

**Comment by Bishamon1987** [comment]
Yes im using Crankshaft. 
But I can make screenshot from /dev/video0 when ./cam_overlay.bin is not running. I also can make regular screenshot from crankshaft environment. I didnt try using screenshot of android auto though.
The thing is, I want to make a script that checks if the camera is turned on or not. Its connected to a video grabber with chipset utv007. So the dev/video0 will be on all the time. 
Maybe you have an idea how to check if the videograbber is getting any input?

**Comment by hawkeyexp** [comment]
the screenshot feature was introduced for better gui documentation etc. :-)
