### ISSUE TITLE
Add/Change CS Classic Buttons

### ISSUE THREAD

**Issue by Bishamon1987** [htruong/crankshaft#324]
Is it possible to reprogram a button in Crankshaft classic view? Or add a button in classic view.
I want to change the view button so i can also use Waze (https://github.com/sashakh/waze) when i don't have a android phone onboard.
This might be even a great idea for crankshaft to add crankshaft.

**Comment by haywirephoenix** [comment]
I'd like to know about ui customization too. Where is the classic ui in the source code?


Also please don't phase out classic ui. Myself and many others prefer it .

Ps: yes I asked this on the reddit page as requested but it's not monitored

**Comment by hawkeyexp** [comment]
- The ui is located in src/autoapp/ui/mainwindow.ui
- The classic ui won't phase out - you noticed it i still there also in ng cause i know many love's the clasic style. 
- About the waze project: it is a very old port, last changed in 2017 and it is conflicting with what cs is designed for - cs is designed to primary run android auto and there you can maps and waze on the android side.

**Comment by Bishamon1987** [comment]
I tried to find the file using Find in terminal and via cyberduck but I
just can't find the folder /src nor can't I find the file mainwindow.ui
What am I doing wrong?


Op ma 22 apr. 2019 22:38 schreef hawkeyexp <notifications@github.com>:

**Comment by hawkeyexp** [comment]
https://github.com/opencardev/openauto/blob/crankshaft-ng/src/autoapp/UI/mainwindow.ui
