### ISSUE TITLE
After 2 minutes it returns to cranckshaft NG

### ISSUE THREAD

**Issue by michaelbeatrici** [htruong/crankshaft#329]
Phone: Honor 10 View Lite
Phone OS: 8.2.0
Android OS of the phone: 8.1.0
Cranckshaft version: alpha 4 3\3\19
Raspberry Pi3 with official 7" touchscreen

After 2 minutes it always returns to cranckshaft NG and I have to tap everytime the button for connect the phone via USB. When this happens, it doesn't see for less than a second the phone and then it shows it again.

**Comment by hawkeyexp** [comment]
Check it with next build again and also check power management settings in your phone.
