### ISSUE TITLE
Setting the Time

### ISSUE THREAD

**Issue by Bishamon1987** [htruong/crankshaft#331]
If you need support: Please post on https://www.reddit.com/r/crankshaft/ as this is a bug tracker, not a support forum.

Note: Reporting issues not based on official published builds will be closed without any comment.

- What phone do you have?
Nokia 6.1
- What OS version?
Android 9
- What crankshaft version?
299C16C
- Bug is reproducable

So I saw that the time is being set via the internet. But its 2 hours behind, but the minutes are precise. 
So the time now is 16:27 and crankshaft shows me 14:28.
I set my country at the wifi settings (thought this might be used for the time zones) 
but whatever country i choose it doesnt appear to have any effect on the time. 
I did not reboot though. 

**edit: now I did try with reboot but no luck there.

**Comment by hawkeyexp** [comment]
please check timezone setting behind rtc type in setttings
