### ISSUE TITLE
[Feature Request] make /boot writable over ssh

### ISSUE THREAD

**Issue by haywirephoenix** [htruong/crankshaft#332]
I have crankshaft integrated into my dashboard and it looks great!

It would be really useful if I was able to have write access to /boot when accessing with a lan cable on ssh as there's currently no space to add the sd card extender or a gpio pin. 

Many thanks!

**Comment by haywirephoenix** [comment]
I managed it with the usb stick devmode file, so no worries. Thanks again!

**Comment by hawkeyexp** [comment]
hint: in live system you can use `crankshaft boot unlock|lock` :-)
