### ISSUE TITLE
Conditional cmdline.txt

### ISSUE THREAD

**Issue by haywirephoenix** [htruong/crankshaft#333]
Hey there,

Is it possible to show the boot text based on the condition that developer mode is enabled?

The only way that I've been able to succesfully hide all of the boot log is to use:

fbcon=map:2

It would be great to have this disabled if it detects devmode

**Comment by hawkeyexp** [comment]
no sorry - some parts will stay visible in some conditions. Normally bootup is showing a splash and a animation during boot. By conditions like script is setting up for you like during rstore or if a flash file is etected system switches to console visible to let you now what's going on. A wanted bahaviour. Possible some small reworks will be done th reduce the possible situations where the shell is shown.
