### ISSUE TITLE
Navigation audio changes to phone speaker after call

### ISSUE THREAD

**Issue by tehniemer** [htruong/crankshaft#338]
- What phone do you have?
OnePlus 6

- What OS version
Pie

- What crankshaft version?
Alpha 4

- Steps to reproduce the bug, if you're planning to report a bug. Please indicate whether the bug is always repoducible.
Start navigation in crankshaft, make or receive call through vehicle Bluetooth, end call, navigation audio is output through phone speaker not crankshaft.

**Comment by hawkeyexp** [comment]
audio routing is in some cases a problem not working as expected. No solution currently.
