### ISSUE TITLE
Request to have colour preset's or saturated mode

### ISSUE THREAD

**Issue by a-haan** [htruong/crankshaft#34]
I'm used to OLED screens, the 7" official touchscreen is very washed out colour wise, having the option to make it more vibrant would be ace!

**Comment by htruong** [comment]
Well, this is not an OLED screen -- But how about this?

https://www.amazon.com/SmallHD-MON-702-OLED-inch-Display-Monitor/dp/B06XJ9D5D8

;-)

**Comment by parkerlreed** [comment]
I think the point @htruong is trying to make is that there's not much you can do to colors to make a dull screen better. (Plus does the Pi even have control over that?)

**Comment by htruong** [comment]
Well, with regrets, this will be the first issue I won't fix -- I just can't see any way I can fix this. Please let me know if you have better ideas how to get around this. :(
