### ISSUE TITLE
Navit support / integration in Crankshaft-NG

### ISSUE THREAD

**Issue by danielsteiner** [htruong/crankshaft#340]
Hi everyone, 

I have my raspberry and 7" screen sitting on my cars dashboard and I sometimes lend my car to my dad or stepmom (it was hers, they gave it to me since I need it more than they do). The thing is: I am sure, they don't want to fiddle around with Android Auto and so I thought supporting Navit (an open source turn-by-turn navigation for Linux) would be nice as well. 

Since Crankshaft runs on Raspbian, Navit should work as well. Do you guys think, that this project would benefit from that? I mean there already is a media player (which could be prettified a bit) and with Navit and FM / DAB + support it could be a complete headunit replacemment. 
What do you guys think?

**Comment by hawkeyexp** [comment]
I can follow your idea but: long tims ago i was also playing with navit but no nice solution i think.
The second thing: the project should primary drive android auto - the offline player is a part which is often used cause for short routes you know there is no navigation needed.
About the look and feel: yes it's not perfect but it will get some more love in the future.
