### ISSUE TITLE
[Feature Request]  microG native support

### ISSUE THREAD

**Issue by ghost** [htruong/crankshaft#341]
Hello! I wonder if anyone else is interested in supporting [microG](https://github.com/microg) project-enabled devices?
microG aims to re-write some of Google's APIs to make android devices usable without proprietary Google components. They haven't implemented AndroidAuto API yet(and I don't know if the work is going) But maybe it would be possible to replace Google API with something lighter and developer-friendly just between these two awesome projects...

**Comment by hawkeyexp** [comment]
cs is working with the g-services cause it's based on openauto.
