### ISSUE TITLE
.iso file not readable

### ISSUE THREAD

**Issue by agnoam** [htruong/crankshaft#344]
The latest release: `Crankshaft OpenCarOS NG Alpha-4 2019-03-03` not working on etcher.
and the windows cannot open it.
The error is: the file is corrupted or unreadable

**Comment by parkerlreed** [comment]
Seems to work fine here. Are you using the img? You mentioned iso

![image](https://user-images.githubusercontent.com/841440/58282655-522efc00-7d74-11e9-972d-7620b1f24db8.png)

**Comment by agnoam** [comment]
yes it is

**Comment by agnoam** [comment]
But I got this error from Etcher: 
![image](https://user-images.githubusercontent.com/6377503/58283580-4b72aa00-7db1-11e9-9756-50cf76029af1.png)

What should I do ?

**Comment by parkerlreed** [comment]
Maybe try Win32DiskImager/Rufus? I haven't dealt with Windows in so long, I'm honestly not sure.

Also maybe try a redownload in case something messed up there (you can check the img md5 against the md5 file provided)

**Comment by agnoam** [comment]
Thanks a lot its worked with Rufus 👌
