### ISSUE TITLE
Crankshaft NG on 10.1inch LCD touchscreen

### ISSUE THREAD

**Issue by tesmnorth** [htruong/crankshaft#348]
Hello,

I am using last version of Crankshaft NG with raspberry pi 3 and waveshare 10.1 inch LCD touch screen. Touch screen is working very well and screen size is ok. But, there is a problem like this: 

![WhatsApp Image 2019-06-08 at 13 19 36](https://user-images.githubusercontent.com/20282905/59145731-9109b680-89f0-11e9-9d01-28c0c2e5bd5a.jpeg)

There is a blue rectangle in the middle of screen. How can I fix this?

Thanks.

**Comment by hawkeyexp** [comment]
it's the non scaled default background of 800x480. As quickfix replace the images in /boot/cran kshaft-*.png with resized to your native screen size.

**Comment by hawkeyexp** [comment]
for next release a auto resize will be added

**Comment by tesmnorth** [comment]
> for next release a auto resize will be added

It will be more user-friendly. Thanks. Now, I resized png files.

**Comment by tesmnorth** [comment]
I have an one more question about touch screen. If I want to click any button by touch screen, button is not working. But, If I double-click, It is working. I search any option for this. But I couldnt find. How can I resolve this double-click problem.

**Comment by hawkeyexp** [comment]
bg resize released. for double clock issue please create a new issue. thx.
