### ISSUE TITLE
X11 Mode Problem 

### ISSUE THREAD

**Issue by tesmnorth** [htruong/crankshaft#351]
Unfortunely, X11 mode is not working. I changed START_X11=0 to START_X11=1 in `crankshaft_env.sh` file. I need to X11 mode for touching screen of my lcd screen.

**Comment by JoelBrenstrum** [comment]
I had a similar issue. I found if I booted in EGL, SSH'd in and enabled X11 then ran 
`sh /opt/crankshaft/service_openauto.sh` I would get a crash message.
setting the environment variable 
`export QT_DEBUG_PLUGINS=1` 
then gave me detailed logging.

I found I needed to install 
`sudo apt-get install libxcb-icccm4 libxcb-image0 libxcb1 libxcb-keysyms1 libxcb-render-util0 libxcb-xinerama0 libx11-xcb1`
all these libs and then it worked! 

Once you get it successfully working via SSH you can reboot with X11 turned on. 
This allowed me to run `xinput-calibrator` to get my LCD touch working correctly. 

Hopefully this helps

**Comment by chucktastic** [comment]
In my case I had to install all the packages JoelBenstrum lists, plus libqt5x11extras5.  This was with Alpha-5.

**Comment by MarcGodard** [comment]
This did the trick for me :) Thanks guys.

Should we make / add this to a trouble shooting document?

**Comment by tesmnorth** [comment]
Thanks @JoelBrenstrum . But we need to install  libqt5x11extras5 as @chucktastic said. Thanks to all.
