### ISSUE TITLE
Raspberry Pi 4

### ISSUE THREAD

**Issue by Stargazzer** [htruong/crankshaft#353]
The rpi 4 just went on sale today.  Would love to see some comments here if the 4 will work with Crankshaft. :)  
https://www.raspberrypi.org/blog/raspberry-pi-4-on-sale-now-from-35/?fbclid=IwAR1Pxf47WDsVYbR8Amu1oQ_XT20dylTV9mfpYb_Frj_IXLNZnlJU3QCesk0

**Comment by hawkeyexp** [comment]
wrong point - use reddit to brainstorm about
