### ISSUE TITLE
NG5 not booting to devmode

### ISSUE THREAD

**Issue by smartroad** [htruong/crankshaft#354]
I have been trying to get CS to boot into DEV mode, I have put a file called ENABLE_DEVMODE on a usb stick but it just boots into the main screen 😢 I don't have easy access to the SD card and not sure what it means in the wiki where it says:

"Within the Crankshaft settings app, CS Env tab, Enable GPIO, choose a low setting"

I don't see anything that lets me pick a 'low' setting. What have I got wrong?

**Comment by hawkeyexp** [comment]
Wiki is updated for better understanding. Trigger via file seems to have a bug - will check it deeper.
