### ISSUE TITLE
AA trips, but no display/output

### ISSUE THREAD

**Issue by ksgoh88** [htruong/crankshaft#355]
If you need support: Please post on https://www.reddit.com/r/crankshaft/ as this is a bug tracker, not a support forum.

Note: Reporting issues not based on official published builds will be closed without any comment.

- What phone do you have?
Pixel 2
- What OS version?
Android 9 PQ3A.190605.003
- What crankshaft version?
Alpha 5
- Steps to reproduce the bug, if you're planning to report a bug. Please indicate whether the bug is always repoducible.
1.Crankshaft boots into main screen.
2.Plug in phone.
3.Crankshaft detects phone, phone shows connected to car.
4.No AA output on Crankshaft. Press AA button, no response.
5. Unplug phone, and plug back in. Same results.

I have reflashed my SD card with alpha5 and got the same results from a fresh flash. It was working fine until 6/25/2019.

Also forgot all cars on my phone, and did not get the usual setup screen to add Crankshaft to remembered cars. Works on my other Sony AA head unit.

- Please provide any further information that you might find helpful if available.
Running latest build of AA, 4.4.592344
Google Play Services 17.7.85

- Starting with pre4: Boot into dev mode (can be selected in settings).
  Reproduce the possible bug. Create the debug logs by pushing the grey button on bottom of screen.
  Add the created file (/boot/debug.zip) to the issue.
[debug.zip](https://github.com/opencardev/crankshaft/files/3331996/debug.zip)

**Comment by hawkeyexp** [comment]
duplicate - same as #352
