### ISSUE TITLE
No Touch control available

### ISSUE THREAD

**Issue by ghost** [htruong/crankshaft#356]
When I start cranckshaft it works fine, I can do everything until I plug in my phone. Once Android Auto starts, I lose touch control, I can't do anything. Please, can someone give me a hand with this thing? I don't really know why is happening, and how to solve :(

**Comment by danielcrex** [comment]
same thing for me

**Comment by iofirag** [comment]
Seems that you had faces this already open issue https://github.com/opencardev/crankshaft/issues/352

**Comment by hawkeyexp** [comment]
Duplicate of #352
