### ISSUE TITLE
[Bug] Touchscreen not working once AA started

### ISSUE THREAD

**Issue by hitech95** [htruong/crankshaft#361]
- What phone do you have?
Pixel 3A
Redmi 4 Pro - Markw

- What OS version?
Android 9

- What crankshaft version?
Crankshaft OpenCarOS NG Alpha-5 2019-06-08

- Steps to reproduce the bug, if you're planning to report a bug. Please indicate whether the bug is always repoducible.
Connect Phone both Wifi and USB, start AA.
Video Feed is shown but touch is not working.

**Comment by JmanNZ** [comment]
take a look here [https://github.com/opencardev/crankshaft/issues/352](url)

**Comment by hitech95** [comment]
Thanks, See #352
No idea why the search didn't have shown the open issue to me.
