### ISSUE TITLE
raspberry pi android auto touch not working crankshaft

### ISSUE THREAD

**Issue by maheshrohit** [htruong/crankshaft#363]
hey guys
            im using raspberry pi 3 7inch display with DSI video mode.
when i connect my phone, everything working fine, but the touch is not working. i tried with normal display, the touch is fine, only on android auto touch is not accessing. please help me.
is there anything i need to configure.
crankshaft 2018 3-13

**Comment by Maju3** [comment]
https://github.com/opencardev/crankshaft/issues/352

**Comment by abraha2d** [comment]
Known issue, there will be a fix in the next build. Please see #352.
