### ISSUE TITLE
problem connecting to WiFi hotspot of phone

### ISSUE THREAD

**Issue by Bishamon1987** [htruong/crankshaft#373]
I changed the WiFi information in crankshaft_env.conf  (not sure this is spelled right)
I tried the first one which should be used for home network.
Of course I tried the second also.
Both have me no luck after changing the settings and rebooting.

**Comment by ldehaas1612** [comment]
Hi Bishamom, I've had the same issue a while back and figured out that the file the wifi passwords are saved in does not get renewed. What I've done to get this fixed was reflash the SD card with the latest version of crankshaft and before continuing editing the SSID and password in the appropriate file. Then after first time boot these credentials are saved somewhere else and won't be reloaded untill reinstall. Hope this helps you out!

**Comment by Bishamon1987** [comment]
Where should this file be located, then I can put it in with sudo nano filename I guess

**Comment by ldehaas1612** [comment]
Okay, I've looked it up for you againand here it is:
Normally you would edit the settings for the wireless network in the /crankshaft/crankshaft_env.sh file. However after initial boot these settings are exported and encrypted into wpa_suplicant.conf, network0.conf and network1.conf if you got a second network setup.
Just reinstall crankshaft, edit the crankshaft_env file with the appropriate settings on your computer, then insert the card into the pi and boot. Hope this helps!

**Comment by abraha2d** [comment]
When changing WiFi related settings in crankshaft_env.sh, make sure you also set `WIFI_UPDATE_CONFIG` to `1` to properly update the WiFi information in wpa_supplicant.

**Comment by ldehaas1612** [comment]
Aaah, that explains the reloading settings from the file issue! Thanks for clarifying!

**Comment by abraha2d** [comment]
@Bishamon1987 does this solve the issue?

**Comment by Bishamon1987** [comment]
It did thanks!
