### ISSUE TITLE
Enhancement: reduce audio judder when exiting Android Auto

### ISSUE THREAD

**Issue by gcharlie** [htruong/crankshaft#375]
Theirs a very jarring audio glitch that happens when you exit Android Auto while audio is playing. I assume this has to do with the sound buffer and/or the audio stream coming from the phone, since the glitch just sounds like the last few bits of audio looping for a second or two. I'm not sure if this is a phone side discrepancy, but has anyone else experienced this?

**Comment by abraha2d** [comment]
Personally, I haven't. Do you mean exiting android auto by pressing the Exit / Return to Crankshaft-NG inside Android Auto, or just by pulling the USB cable?

EDIT: Tested both methods of exiting multiple times, and was not able to reproduce.

**Comment by smartroad** [comment]
This happened on "professional" equipment to. I have a hire car at the moment and it will sometimes leave the audio playing for a short time. I think it is an issue with AA rather than CS.

**Comment by abraha2d** [comment]
@gcharlie Tested both ways, and wasn't able to reproduce the glitch. What combination of phone/hardware are you using? If other people are experiencing the same thing, maybe we can find that it only happens with certain setups...

**Comment by smartroad** [comment]
It happens with me both with CS and with Mitsubishi head unit. Phone wise, S10e, Nokia 8 and Samsung A(some number, its works phone lol)

**Comment by gcharlie** [comment]
Fair enough, that makes sense. i guess there no need to keep this open then.

**Comment by abraha2d** [comment]
Yes, I guess it's an underlying AA issue if it's happening with stock AA headunits.
