### ISSUE TITLE
Connect to Car with Bluetooth

### ISSUE THREAD

**Issue by Blackei** [htruong/crankshaft#382]
Hi,
Is it possible to Connect crankshaft for Audio Out with a car Radio with Bluetooth?

**Comment by agnoam** [comment]
I did something like this.
for me, it worked by those steps.

- Connect your phone to the bluetooth device
- Go to Crankshaft settings
- Go to the input tab
- Uncheck all channels of the top (Speech etc.)

Good luck

**Comment by matt2005** [comment]
Yes see above post
