### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by muratcali** [htruong/crankshaft#385]
Hi,

I tried different versions of Crankshaft on my pi. But on every version I just get a black screen. When I install raspbian on my USB it just works perfectly, but everytime I try to run Crankshaft it just doesnt do anything. I only see a black screen. Im using a Raspberry pi 3B, with the official 7inch touchscreen

**Comment by Bishamon1987** [comment]
I need to l2r..
So it's connected by DSI right? 
Try the HDMI see if it works.
I can't use the rca output but HDMI works fine.
So maybe the output is hardcoded py accident?

**Comment by muratcali** [comment]
Nope, HDMI also doesnt work.. My screen is still black

**Comment by Bishamon1987** [comment]
Tried changing settings like x11 or egl. Changing config.txt

**Comment by muratcali** [comment]
It just doesnt boot.. I enabled splashscreen.. I see the usual colored splash screen from the Rpi then it turns black and nothing happens..

**Comment by Bishamon1987** [comment]
The screen turns of for about 1.5min then crankshaft is running. It's to hide the startup lines

**Comment by muratcali** [comment]
Still no succes.. I still have the black screen. I will record it when I'm back home, and send the config file, So you can understand me better.

**Comment by muratcali** [comment]
Here is the Video: https://youtu.be/EQcN-IQjbNg 
I use the latest IMG from https://github.com/opencardev/crankshaft/releases

**Comment by choryuidentify** [comment]
It can be happen by SD card. Trying change card.

**Comment by matt2005** [comment]
Can you try latest release alpha 55?

**Comment by matt2005** [comment]
fixed in alpha7
