### ISSUE TITLE
Day/Night Phone-Controlled is ignored - have to manually set for dark/light mode

### ISSUE THREAD

**Issue by a-haan** [htruong/crankshaft#39]
- What phone do you have? What OS version? Pixel 2 XL, 8.1
- Did you try to enable and run autoapp under X11 dev mode?  Follow this: https://github.com/htruong/crankshaft/wiki/Crankshaft-dev-mode- no
- Please provide any further information that you might find helpful.
none

**Comment by measle** [comment]
Same Problem: LG G4 H815 Running 7.0 (H-ROM V30 PORT V2.2)
Came across this but have not tried it:
https://play.google.com/store/apps/details?id=gb.aahelper.hr

**Comment by smartroad** [comment]
just tried the app on my test bed unit and it seems to work ok

**Comment by ahoneybun** [comment]
Is this controller with the phone? If it is time based it would make sense if the phone controls it. This seems to happen on the 04-01 image as well.

**Comment by htruong** [comment]
Please follow directions on https://www.reddit.com/r/crankshaft/comments/8eze6m/heres_an_app_that_forces_android_auto_to_switch/ to have the mode changed automatically. Huge props to Emil!
