### ISSUE TITLE
Figure out a sensible way to turn on/off the system

### ISSUE THREAD

**Issue by htruong** [htruong/crankshaft#4]
Yanking out the USB cable is dumb and dangerous. Figure out a way to do it more gently.

**Comment by htruong** [comment]
The issue is partially resolved with read-only fs in alpha 0.1.1-2018-02-28. Now there is no more corruption, but users still have to yank the cables to turn the system off.

**Comment by parkerlreed** [comment]
Maybe suggest to OpenAuto to add a poweroff item to the main menu?

**Comment by htruong** [comment]
@parkerlreed  I think the general idea here is "do it and do a pull request, and hope he accepts it" instead of "asking f1xpl to do it for me."

**Comment by parkerlreed** [comment]
That's what I meant. :smile: Could have worded that better.

**Comment by htruong** [comment]
This is now resolved with image 2018-03-02. Now users can turn off the system with the power button on the main UI. Users can also temporarily put it to sleep (disable backlight), so it doesn't look totally ridiculous when the car is parking somewhere.
