### ISSUE TITLE
bad url in wiki for building crankshaft

### ISSUE THREAD

**Issue by Alexplose** [htruong/crankshaft#400]
In this page : 
https://github.com/opencardev/crankshaft/wiki/Building-the-binary-blobs

This url is 404 :
Please refer to https://github.com/htruong/crankshaft/blob/master/COMPILE.md to start.

Maybe I'll need more help on how to build crankshaft, can you please elaborate on how to build.

Thanks

**Comment by egisz** [comment]
Hi @Alexplose, 
I suggest you go to the more fresh fork of this repo https://github.com/fazerxlo/crankshaft
and build using docker container. It worked for me. Instructions are included there.
It took ~45 minutes for me. It's done on PC rather than RPI, so should be faster process.

**Comment by matt2005** [comment]
I'm currently reviewing the build process and will be updating once completed.

**Comment by matt2005** [comment]
fixed, wiki page is for crankshaft  classic so repointed to correct file
