### ISSUE TITLE
command prompt

### ISSUE THREAD

**Issue by clowsglede** [htruong/crankshaft#406]
Hi 
how to open command prompt if i need to add a driver for example?

**Comment by robert5974** [comment]
Use another computer or "remote" computer, using SSH to the Pi ( over network or physically connected via ethernet cable).  SSH is already enabled on the Crankshaft image so you would only need to setup the other end on the remote computer.  You can find more instructions here https://www.raspberrypi.org/documentation/remote-access/ssh/

which has client setup instructions at the bottom via links to whichever platform you will use.

You can also start crankshaft in devmode which is explained in the wiki.

**Comment by matt2005** [comment]
Issue resolved
