### ISSUE TITLE
No Call Audio in Wired Setup

### ISSUE THREAD

**Issue by rtuz2th** [htruong/crankshaft#413]
- What phone do you have?
FxTec Pro1

- What OS version?
Android 9

- What crankshaft version?
Crankshaft OpenCarOS NG Alpha-5.1 2019-08-08

Raspberry Pi 3B+
[UGreen External Soundcard](https://www.amazon.de/gp/product/B01N905VOY/ref=ppx_yo_dt_b_asin_title_o00_s01?ie=UTF8&psc=1)
[CSL Bluetooth Adapter](https://www.amazon.de/gp/product/B01N0368AY/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1)
[Seven Inch Touchscreen](https://www.amazon.de/gp/product/B07YJDSCKR/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1)

Hi,
I don't get call audio working. I know about the Bluetooth Codec problem, I did not even try a full wireless setup yet, call audio does not work in a wired setup. Everything else does - Media Audio, Google Assistant etc all go through my external Audio Card, but Call Audio is still coming from the phone and the phones Mic is picking it up. I tried to connect the phone via bluetooth using an external adapter additional to the wired connection, but this does not work, too. I've looked into [Issue #323 ](https://github.com/opencardev/crankshaft/issues/323) and did everything according to the wiki cited there, but still the same issue. I've got Dev Mode enabled.

**Comment by Permanently** [comment]
Did you find a solution?
