### ISSUE TITLE
Auto updater not working

### ISSUE THREAD

**Issue by matt2005** [htruong/crankshaft#419]
Auto updater not working

**Comment by egisz** [comment]
Also tried to update via USB from `v1-csng-alpha52-buster` to `v1-csng-alpha53-buster` according instructions in [Wiki](https://github.com/opencardev/crankshaft/wiki/Installing-and-Updating). Not working.
According Wiki - MD5 checksum file is required, it is missing in recent releases. I think it's a small fix.
Generated and added manually to USB stick, named same as image name xxx.img.md5: 
```
pi@CRANKSHAFT-NG:/media/USBDRIVES/sda1 $ ls
 v1-csng-alpha53-buster.img   v1-csng-alpha53-buster.img.md5
```
still nothing....
Updated files according old releases name structure:
```
pi@CRANKSHAFT-NG:/media/USBDRIVES/sda1 $ ls
 2020-10-05-crankshaft-ng-E2B068B.img   2020-10-05-crankshaft-ng-E2B068B.img.md5
```
Update was recognized, and update process started, but it never finishes, system rebooted multiple times, and each time goes through update process, but still same old build in Welcome message..

**Comment by matt2005** [comment]
I noticed it wasn'tt working last night, I had a breif look at the code and it's looking for data which is no longer available so I'm re-working the process to fix it. I have already added a fix for the MD5 sums but need to do a new release.

**Comment by matt2005** [comment]
fixed in alpha7
