### ISSUE TITLE
aasdk fix not present in latest build (alpha53)

### ISSUE THREAD

**Issue by egisz** [htruong/crankshaft#421]
Hi,

Tested latest build, but it seems that this fix is not incorporated: 
https://github.com/opencardev/aasdk/commit/76294c53517dbde5126e2b73422698da8892b2fe
Rotate buttons do not work.

I haven't figured 100% how build process works, but I believe prebuilds repo is out of date.
this repo is pointing to [prebuilds](https://github.com/matt2005/prebuilts/tree/cef40eca2bac23ccf33e138d3ea199838e7bcffb) which autoapp is 8 months old...

I saw there is fresh alpha54 prebuilds [branch](https://github.com/matt2005/prebuilts/tree/csng-alpha5.4) with updated [aasdk](https://github.com/matt2005/prebuilts/commit/9627e220e294ecc98a639dbedf143f37bb47a0a3) files, so I tried to replace them in alpha53 image. But it does not change anything.

I believe autoapp needs to be rebuilt too.

**Comment by matt2005** [comment]
Yeah prebuilts out of date, which has caused several issues. I'm in process of rebuilding the prebuilts. I had a few issues with the builds so am about to update them.

**Comment by matt2005** [comment]
I've rebuilt the prebuilts can you try before I promote to the opencardev repo. [Please try newer prebuilts](https://github.com/opencardev/crankshaft/issues/422#issuecomment-706664254)

**Comment by matt2005** [comment]
Resolved in Alpha 5.5 [alpha 5.5](https://github.com/opencardev/crankshaft/releases/tag/csng-alpha5.5)
