### ISSUE TITLE
Wavshare 4.3 Inch Touchscreen Does Not Work 

### ISSUE THREAD

**Issue by matthewconwa** [htruong/crankshaft#423]
- What phone do you have?
Xiaomi Mix Mix 3
- What OS version?
9PKQ1.190321.001
- What crankshaft version?
Crankshaft Openauto 0.2.3 2018-04-18 / Android Auto 5.6.603434-release
- Steps to reproduce the bug, if you're planning to report a bug. Please indicate whether the bug is always repoducible.
Start pi -> Connect Phone -> Map Load 

My config: Raspberry Pi 3B + Waveshare 15932 LCD 4,3"

I have a problem with no touch in Raspberry Pi. In Crankshaft settings touch works well but when I plugged the phone and then google maps lunched I lost touch completely. I tried this fix in [click](https://github.com/opencardev/crankshaft/issues/38#issuecomment-373227859) but without any result. Please look at my config and crankshaft_env files. 

Please help.
[crankshaft_env.txt](https://github.com/opencardev/crankshaft/files/5357289/crankshaft_env.txt)
[config.txt](https://github.com/opencardev/crankshaft/files/5357290/config.txt)

**Comment by matt2005** [comment]
Please try the latest release alpha7

**Comment by matt2005** [comment]
Did the screen work on latest release?

**Comment by matt2005** [comment]
Closing as no further comments
