### ISSUE TITLE
Prebuilts script warning of not found packages (low priority)

### ISSUE THREAD

**Issue by egisz** [htruong/crankshaft#425]
While running 1_prepare_build_system script, it blames not finding packages:
```
./buildsystem/1_prepare_build_system.sh
...
E: Unable to locate package librtaudio5a
E: Unable to locate package librtaudio5a
E: Unable to locate package v4l2-dev
```

They are updated to 

- libv4l-dev (missing)
- and librtaudio-dev (this is already in the script)

**Comment by matt2005** [comment]
I need to push my latest changes. I've already fixed the issue, just busy with work this week.

**Comment by matt2005** [comment]
Updated prebuilt submodule to point the latest prebuilt commit
