### ISSUE TITLE
Rpi4

### ISSUE THREAD

**Issue by mxdlinux** [htruong/crankshaft#430]
Hello everyone 

I have an rpi4, and despite various attempts, the tsl2561 is recognized (this can be seen at boot) but the screen does not change the brightness, I cannot connect to wifi even by modifying the crankshaft_env.sh file and  no connection even wired

**Comment by matt2005** [comment]
What screen are you using?

**Comment by mxdlinux** [comment]
I have the lcd 7 inch touchscreen original raspberry , why?

**Comment by matt2005** [comment]
Related to #436 so closing this one
