### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by KamiSchami** [htruong/crankshaft#432]
Hi, how do i update a running system?  do I have to reinstall everything?

**Comment by matt2005** [comment]
What version are you running at the moment?

**Comment by KamiSchami** [comment]
![20201210_130331](https://user-images.githubusercontent.com/67215246/101897664-2ddf7e00-3bab-11eb-9486-cbff47437616.jpg)

Is this the version?

**Comment by matt2005** [comment]
It's a major update but if you backup the sd card and then connect pi to internet it should detect an update and you will be able to update. Otherwise you could setup another sd card with the latest release  and then copy over the crankshaft folder and edit config.txt for your setup if required.

**Comment by matt2005** [comment]
Did you manage to update?

**Comment by Lotusvball** [comment]
I have the same version and my pi is connected to the internet.  It will not update using the Update option in Cranskshaft.

**Comment by matt2005** [comment]
@Lotusvball @KamiSchami I've just informed the updater about a new version. I'm also checking that it is picking up the update from your specific version.

**Comment by matt2005** [comment]
Try this
1. Enable dev mode
2. SSH into PI
3. Run
```bash
crankshaft update check
```
4. It should say update available
```
Crankshaft Management Tool v2.4.0 is executing command...

Internet connection available

New csmt available!
New openauto available!
New system image available!

Done.
pi@CRANKSHAFT-NG:~ $
```
5. Run
```bash
crankshaft update csmt
```
6. Insert usb flash named CSSTORAGE
7. Run
```bash
crankshaft update system
```
8. You should see it downloading the update to the flash media.
9. Run
```bash
sudo reboot
```
10. The pi will reboot and detect the update on the flash media and apply it. This will take a while 20+mins depending on SD card
11. if the pi hangs at the crankshaft screen try adding the following to the config.txt
```text
[pi4]
# Enable DRM VC4 V3D driver on top of the dispmanx display stack
dtoverlay=vc4-fkms-v3d
max_framebuffers=2
[all]
dtoverlay=vc4-fkms-v3d
```

**Comment by matt2005** [comment]
Please let me know if you experience the pi hanging.

**Comment by KamiSchami** [comment]
Ok great, i will test it. Thank you.

**Comment by matt2005** [comment]
Did you manage to update?

**Comment by Lotusvball** [comment]
I ended up doing a new image and using that.  It works great.  Much more responsive.
