### ISSUE TITLE
Waveshare 7" Touchscreen 1024x600 not working

### ISSUE THREAD

**Issue by luizricardo-co** [htruong/crankshaft#433]
Hi guys, I installed the last release Crankshaft OpenCarOS csng-alpha7 2020-10-26 and not working on LCD 7inch. When I connect on my HDMI monitor works great, but when I connect on my HDMI LDC on show blue screen.
I putted sniping code on my config file and nothing.

hdmi_group=2
hdmi_mode=87
hdmi_cvt 1024 600 60 6 0 0 0
hdmi_drive=1

Anybody can help me? 
Thanks!

**Comment by matt2005** [comment]
Can you share the config.txt from the sd card

**Comment by matt2005** [comment]
I've attached my config.txt which is for a 7" 1024x600 screen, please try it.
[config.txt](https://github.com/opencardev/crankshaft/files/5811177/config.txt)

**Comment by matt2005** [comment]
Please try release [alpha7.2](https://github.com/opencardev/crankshaft/releases/tag/csng-alpha7.2)
