### ISSUE TITLE
Brightness control in Crankshaft

### ISSUE THREAD

**Issue by devangapatel** [htruong/crankshaft#44]
Would be nice to be able to control brightness of the Pi on the crankshaft UI without having to go into dev mode. This would help several of us from having to go thru adding a physical momentary button (like what everlander did and controlling this thru the GPIO ) 

Maybe even set a brightness profile based on time of the day?

**Comment by htruong** [comment]
Manual brightness control is possible. Automatic brightness control is impossible. Refer to https://www.reddit.com/r/crankshaft/comments/84drzu/crontab_and_crankshaft/dvoqo41/

**Comment by devangapatel** [comment]
Manual it is then! But we need to be able to do this without the need of GPIO or external physical switches. :-)

**Comment by htruong** [comment]
Done as of 0.2.1!
