### ISSUE TITLE
Screen Not Responding In Night Mode

### ISSUE THREAD

**Issue by codydjohnston** [htruong/crankshaft#442]
When I turn night mode on (using the button in the menu) the screen goes black. I assumed that was normal and that touching the screen would turn it back on, but the when I touch the screen nothing happens. I have tried connecting my phone when this happens and I get the connected to android auto notification (on my phone, a Samsung Note 9) , but the screen is still black and not responding. I am using the official raspberry pi 7 inch touch screen and a pi 3 b+.

**Comment by matt2005** [comment]
What version are you using? How are you connecting the phone?

**Comment by codydjohnston** [comment]
I am using the newest version and connecting via a usb a to usb c cable.

**Comment by matt2005** [comment]
@Ch3ddar77994

Please try release [alpha7.2](https://github.com/opencardev/crankshaft/releases/tag/csng-alpha7.2)

**Comment by matt2005** [comment]
See #495
