### ISSUE TITLE
Brightness goes to 0 when using Moon / Sun icon

### ISSUE THREAD

**Issue by Sono-Gomorrha** [htruong/crankshaft#467]
- What phone do you have: Pixel 3a

- What OS version: Android 11

- What crankshaft version: CSMT 2.4.
- CS Base Tab in Settings says version f8d7ba3; Build Date: 2020-10-26

- Steps to reproduce the bug, if you're planning to report a bug. Please indicate whether the bug is always reproducible.
- I try to set the brightness using the moon and sun icon in the homescreen. I tap the moon icon and the display brightness goes to 0. I can't see anything and running crankshaft brightness get level also returns 0 as a value. When I then run e.g. crankshaft brightness set 55 I get a level of 55 and I can see the sun icon. Tapping the sun icon will make the screen go to a brightness level of 31 (min setting in config is 30). I'm using a raspberry pi 3b+ and the official raspberry pi touchscreen.

Brightness settings are default and unchanged by me in crankshaft_env.sh:
# brightness values
BR_MIN=30
BR_MAX=255
BR_STEP=25
BR_DAY=231
BR_NIGHT=90

Custom Brightness Control is left empty.

**Comment by matt2005** [comment]
See #495
