### ISSUE TITLE
audio call problem

### ISSUE THREAD

**Issue by DavideVairetti** [htruong/crankshaft#469]
Hi guys, I have some audio problems with the new alpha version of crankshaft. The music volume has low volume (but with high quality compared with the old alpha version) and the call audio is something horrible, I can't hear pretty much nothing. Any idea about a solution? 

Phone: One Plus Nord
OS version: CrankShaft Alpha 7.2

**Comment by nperrachione** [comment]
I have the same problem

**Comment by DavideVairetti** [comment]
I solved the music volume problem with an usb audio card but I can't find any solution for the call audio. I read that is releated to some protocol used by google and I think it's a bug already know.
