### ISSUE TITLE
Cannot select GPIO27 for "ignition pin"

### ISSUE THREAD

**Issue by Compizfox** [htruong/crankshaft#474]
As per [the wiki page](https://github.com/opencardev/crankshaft/wiki/Boot,-reboot-and-shutdown-the-Pi-with-ignition-key), I made a circuit to pull GPIO27 low when the key is removed from the ignition.

However, in the settings menu the select box for "ignition pin" goes from 1 to 26, thus I'm not able to select GPIO27.

I tried to manually set `IGNITION_PIN=27` in `crankshaft_env.sh`, but it is not working. Also, the comment in that file contradicts the wiki:

> This pin must be low to keep system running. If high for > IGNITION-DELAY (seconds) system will do a shutdown

which confused me, since I made the circuit so that the pin is pulled **high** with the ignition on (so the system should shutdown when the pin is **low** for the delay).

I can of course still manually shutdown the RPi. However, a second problem is that the RPi keeps powering the USB port when it's shutdown, which means the entire system still draws about 0.190 A (at 12V, so ~2.3 W) at that point. That is still to high to my taste to run 24/7 because of the risk of sucking the car battery dry when left for multiple days. Is there any way to get the RPi to cut the power to the USB port when halted, or is it hard-wired to the 5V line?

**Comment by matt2005** [comment]
i'll take a look at it

**Comment by Stimpson-J-Cat** [comment]
I had this set up on a 3B+. I had a power supply set up on the accessory circuit in my truck that stayed powered for 7 min after shutdown. The Pi was connected to that. I had a relay set up that powered with ignition and set GPIO3 low (to ground from pin 9) and that would start the Pi, then when I shut the truck down, the relay would release, ground would drop off GPIO3 and the Pi would shut down, then 7 min later, the power supply would lose power and then no more draw. That 3B+ died and I replaced it with a 4B and this set up no longer works. I even modified the wiring on my relay to match the Wiki and set GPIO3 low when ignition on and GPIO27 low when ignition off and all that happens is the Pi will boot and 10 seconds later, it shuts down (10 seconds is the delay I have set). It seems that any change in the state of GPIO3 makes the Pi boot; if I set it to low, it boots then shuts down in 10, and if I remove the ground from GPIO3 it boots again then shuts down in 10 seconds.  I also had a similar relay set up to GPIO12 to dim the display when the lights were on and that no longer works on the Pi 4B either. Am I better off going back to a 3B+ and not using the 4B?

**Comment by matt2005** [comment]
I've found the issue and am working on the fix.

**Comment by matt2005** [comment]
Does the latest pre-release version work if you manually set it in the file

**Comment by matt2005** [comment]
Release 7.4 fixes GPIO, you should be able to manually enter it in the config file. Please reopen if it doesn't work.
