### ISSUE TITLE
What is underhood? Can I use it without phone in the car?

### ISSUE THREAD

**Issue by Dukobpa3** [htruong/crankshaft#48]
I wanna to use it as standalone headunit.
I wanna set up at least standalone media.
Maybe any other app which is not depends to my phone.
And sometimes launch AA when it needed.

Is it possible with this distribution?

**Comment by parkerlreed** [comment]
Cranksgaft uses OpenAuto which in turn streams everything FROM the phone. So the phone is required in that case.

There are other projects which aim to be standalone headunits.

http://headunit.viktorgino.me/

https://github.com/viktorgino/headunit-desktop

https://github.com/viktorgino/headunit-gui

**Comment by Dukobpa3** [comment]
Thanks for the links!
