### ISSUE TITLE
Cannot get Ignition or Dimmer pins to work on RPi 4B

### ISSUE THREAD

**Issue by Stimpson-J-Cat** [htruong/crankshaft#484]
- What phone do you have?  LG G8 ThinQ but problem exists without phone attached

- What OS version? Android 10, but not really relevant.

- What crankshaft version? Latest, from 2/2021

- Steps to reproduce the bug, if you're planning to report a bug. Please indicate whether the bug is always repoducible. The bug is always reproducible. I have GPIO enabled, ignition pin set to GPIO3 and Day/Night pin set to GPIO12. I have relays set up to provide ground from PIN9 to GPIO3 with ignition power and provide ground from PIN34 to GPIO12 when dashboard lights go on. Neither of these functions work. Picture and diagram:

![20210805_184223_HDR](https://user-images.githubusercontent.com/88469570/131038133-a6b90711-6519-4383-ab6f-69836d07bd47.jpg)
![20210805_184232](https://user-images.githubusercontent.com/88469570/131038135-bf0f55d9-e425-43d9-9de7-38ed183825a6.jpg)

- Please provide any further information that you might find helpful if available. I had a 3B+ that fried (my fault) and all worked on that but not the 4B. I pulled the 4B and replaced it with a 3B (not 3B+) and it works as it should so it seems the 4B doesn't.  The diagram shows GPIO27 connected as well, but it doesn't work with or without that. On the 3B, it doesn't need to be connected to work but I saw in the Wiki that the on/off should be GPIO3 and 27 so I thought I would try it. Didn't work.

**Comment by matt2005** [comment]
I've found the issue and am working on the fix.

**Comment by matt2005** [comment]
Please try alpha 7.4

**Comment by matt2005** [comment]
I've tested the daylight pin to GPIO24 and it works on a RPI4B 8GB using the alpha 7.4.
Here is my output when the GPIO circuit is open.
```
pi@CRANKSHAFT-NG:~ $ csmt gpio status
Crankshaft Management Tool v2.4.0 is executing command...

Dev Mode
---------------------------------------------------------------
GPIO: -- - State: disabled

Invert Mode
---------------------------------------------------------------
GPIO: -- - State: disabled

X11 Mode
---------------------------------------------------------------
GPIO: -- - State: disabled

Android Connected
---------------------------------------------------------------
GPIO: -- - State: disabled

Ignition State
---------------------------------------------------------------
GPIO: -- - State: disabled

Daynight State
---------------------------------------------------------------
GPIO: 24 - State: Triggered

Done.
```

**Comment by matt2005** [comment]
@Stimpson-J-Cat have you been able to retest?

**Comment by matt2005** [comment]
Assuming fixed as no further comments
