### ISSUE TITLE
Crankshaft use wireless like carsifi

### ISSUE THREAD

**Issue by kabelklaus** [htruong/crankshaft#485]
is it possible to use crankshaft wirless like carsifi.
Or is it possible with the hotspot function by crankshaft?

**Comment by matt2005** [comment]
Whats carsifi?

**Comment by kabelklaus** [comment]
It's an Adapter. 
He is connect to android car by a normal phone cable and your phone by Bluetooth and wireless. 
Now, your phone is automatically connect with Android car and you don't need a phone cable. 

https://carsifi.com/

**Comment by matt2005** [comment]
you can skip the initial cable
https://github.com/opencardev/crankshaft/wiki/Android-Auto-Wifi#enabling-android-auto-over-wifi-with-crankshaft

**Comment by kabelklaus** [comment]
I connect to crankshaft via the hotspot and start the Android auto server. The Android auto settings screen popped up at the beginning, but before I could confirm anything, I was suddenly on the phone's homescreen and crankshaft doesn't switch to Android auto mode.
Nothing happens at all. I can't even press the client connect button in crankshaft anymore.

**Comment by kabelklaus** [comment]
I don't know why, but now it works.
