### ISSUE TITLE
Still hear audio crack especially when lounder music is played

### ISSUE THREAD

**Issue by chaoman** [htruong/crankshaft#50]
- What phone do you have? What OS version? HTC 10 (2016) running Android 8.0.0
- Did you try to enable and run autoapp under X11 dev mode?  Follow this: https://github.com/htruong/crankshaft/wiki/Crankshaft-dev-mode. Yes. I tried to adjust output volume using alsamixer but still without a luck
- Please provide any further information that you might find helpful.

First of all, I am using Raspberry Pi 2 and connecting my HTC 10 running Android 8.0 through the HTC OEM USB Type-C cable.

As for the sound card, I am using an external USB sound card Sound Blaster Play! 2. I could hear crackles when I play music through Google Play Music. The crackles and pops in the beginning of audio output are very noticeable. I am using the crankshaft-2018-03-13.zip build. 

I also tried to  reproduce this issue with Raspberry Pi 3 and same Sound Blaster Play! 2 USB sound card and this could be reproducible. With Pi's built-in 3.5mm output jack, this problem cannot be reproducible.

**Comment by htruong** [comment]
@chaoman for the time being, manually editing `/etc/pulse/default.pa` and remove the line `set-sink-volume 0 52428` will solve your problems. I am figuring out ways for Crankshaft to be more intelligent about custom hardware detection.

**Comment by chaoman** [comment]
Thank you for answering. I just tried to comment out `#set-sink-volume 0 52428` in `/etc/pulse/default.pa`, but I could still hear the crackle. Do you have other suggestions?

**Comment by htruong** [comment]
Oh, so that wasn't due to the volume level... First, try editing `/etc/pulse/daemon.conf`, you should see:

```
default-fragments = 8
default-fragment-size-msec = 5
```

Try increasing both to 10, restart, see if that helps. If it still doesn't, try editing `/etc/pulse/default.pa` and removing `tsched=0` from it. It's due to the customization done [here](https://github.com/htruong/crankshaft/blob/master/scripts/customize-image-pi.sh#L59) on Crankshaft.

**Comment by htruong** [comment]
Great to hear that it works for you. Audio in linux is such a pain :)
