### ISSUE TITLE
feature request: manual or automatic brightness control

### ISSUE THREAD

**Issue by Mearman** [htruong/crankshaft#52]
day and night mode is brilliant but the brightness is still blinding in night mode.

would it be possible to add manual, time or sunrise/sunset brightness control, please?

**Comment by parkerlreed** [comment]
Please check already open tickets before submitting https://github.com/htruong/crankshaft/issues/44

**Comment by parkerlreed** [comment]
See also: https://github.com/htruong/crankshaft/issues/49#issuecomment-375015880

**Comment by Mearman** [comment]
Oh I don't know how I didn't see those. Thanks @parkerlreed

**Comment by htruong** [comment]
Done!
