### ISSUE TITLE
Cam_overlay doesn't work

### ISSUE THREAD

**Issue by maskaz** [htruong/crankshaft#524]
Platform:
Raspberry Pi 3

Version checked:

2019-08-08-crankshaft-ng-E2B068B

With OpenGL enabled: * failed to add service - already in use?
With OpenGL Legacy enabled: Cannot open 'shader-MJPG.frag': 2, No such file or directory

Version checked:

2021-09-22-crankshaft-ng-ea9e288
With OpenGL enabled: * failed to add service - already in use?
With "dtoverlay=vc4-fkms-v3d" removed: Cannot open 'shader-MJPG.frag': 2, No such file or directory

**Comment by maskaz** [comment]
I have found workaround.
Those entries needed to be commented out:

[pi4]
dtoverlay=vc4-fkms-v3d
max_framebuffers=2

[all]
dtoverlay=vc4-fkms-v3d

Regards

**Comment by Ramortada** [comment]
@maskaz from what type of camera were you using please ?
