### ISSUE TITLE
How to save Settings

### ISSUE THREAD

**Issue by pumpkintechlabs** [htruong/crankshaft#53]
- What phone do you have? What OS version? - Pixel XL 8.1
- Did you try to enable and run autoapp under X11 dev mode?  - No

Have to disable the audio channels on every startup for the Bluetooth Audio and Voice to go through the car stereo. Untick the check boxes for Media and Speech channels then hit Save, reboot - the checkboxes are checked again.

**Comment by htruong** [comment]
The settings stick if you shut it down by the shutdown button. When you press it, it will save settings and shut down :)

**Comment by htruong** [comment]
I assume you got it figured out, so I will close this ticket :)
