### ISSUE TITLE
Brightness problem

### ISSUE THREAD

**Issue by borsosgy** [htruong/crankshaft#533]
- What phone do you have?  Samsung A52

- What OS version?  I use the image: 2021-09-22-crankshaft-ng-ea9e288.zip  + Official PI 7" Touch + RPI 3 B+

- Steps to reproduce the bug, if you're planning to report a bug. Please indicate whether the bug is always repoducible. : 
  If you set a brightness day more than 100, only the last two digits are set. 
  199--> 99 
  210--> 10
  255 --> 55

**Comment by matt2005** [comment]
related to #515

**Comment by techdev5521** [comment]
I can recreate this issue but I don't think it is related to the light sensor.
