### ISSUE TITLE
Cannot rotate Waveshare 7.9 inch screeen

### ISSUE THREAD

**Issue by Pavlo458** [htruong/crankshaft#534]
Hello,
I have an issue with my screen orientation. I've tried alpha 7, 7.1 and 7.2 and cannot rotate my waveshare 7.9 display on any of them. It is by default in portrait view and I want to have it in landscape.
Do you know what I should try?

[config.txt](https://github.com/opencardev/crankshaft/files/8008466/config.txt)

**Comment by Gwx76** [comment]
Hello, for rotation with cranshaft here is my config file to compare with yours, mine is very stable.
don't forget to update the "crankshaft_env.sh" file
### OpenAuto ###
# Start OpenAuto in X11 or EGL
# By default, EGL, but if you can't get it to work, do X11
START_X11=1
[config.txt](https://github.com/opencardev/crankshaft/files/8251743/config.txt)
