### ISSUE TITLE
Feature Request - detect phone connection on boot. 

### ISSUE THREAD

**Issue by the-mentor** [htruong/crankshaft#55]
I run the latest version of crankshaft and found that if the phone is connected to the USB before the pi is connected after the pi boots it won't launch android auto. 
I find it quite annoying since I want to connect my phone when I get to the car before I start it and the pi boot up. 
When doing so the phone is not detected until I unplug it and plug it back. 

Let me know if you have any questions. 
Thanks for the amazing work! 
-dm

**Comment by Elmardus** [comment]
This feature was just added in the new release of openauto. Maybe it will come to crankshaft soon?

**Comment by htruong** [comment]
Done as of 0.2.1!
