### ISSUE TITLE
Raspberry Pi 2B

### ISSUE THREAD

**Issue by atomdude** [htruong/crankshaft#567]
i followed installation instructions, tried to install on Raspberry 2B and it failed saying that failed to start auto......

i read that crankshaft should work on raspeberry version 2B any ideas why?

**Comment by matt2005** [comment]
Could you try this image [pi2 image](https://github.com/opencardev/crankshaft/releases/download/untagged-abf8030d8708ae211544/2022-02-04-crankshaft-ng-496df4a-pi2.zip)

**Comment by lazyjavvy** [comment]
@matt2005 Thank you very much for working on this issue.
The latest image for pi 2 (2022-02-04-crankshaft-ng-496df4a-pi2.zip) works for me after following the instructions for updating QT at https://github.com/opencardev/crankshaft/issues/450#issuecomment-1008029456
It seems that the Qt binaries in the release image are still for ARMv8.

**Comment by matt2005** [comment]
Ah, i think the build has mixed up the pi2 pi3/4 QT libraries. Can you try the other image? @lazyjavvy

**Comment by lazyjavvy** [comment]
The other image works for pi 2 model B v1.1

**Comment by robertw** [comment]
could you please show me which pi 2 image works thank you

**Comment by lazyjavvy** [comment]
[2022-02-04-crankshaft-ng-496df4a.zip](https://github.com/opencardev/crankshaft/releases/download/csng-alpha7.5/2022-02-04-crankshaft-ng-496df4a.zip) works for pi 2 model B v1.1

**Comment by matt2005** [comment]
I'm building the new images. They should be ready tomorrow. Hopefully the fix has resolved the filename mixup

**Comment by robertw** [comment]
thank you guys got it working pi 2 !

**Comment by matt2005** [comment]
please try [2022.09.12.1](https://github.com/opencardev/crankshaft/releases/tag/v.2022.09.12.1) that should have the correct naming

**Comment by atomdude** [comment]
ok i will try it, i am travelling now and will do in the next couple of weeks.

Thanks
________________________________
