### ISSUE TITLE
USB keyboard not working

### ISSUE THREAD

**Issue by wiciu15** [htruong/crankshaft#57]
generic usb keyboard, works well plugged into PC, when plugged into raspberry pi stops working after a minute or two

**Comment by htruong** [comment]
The Pi is known to be picky about the keyboard it likes. But that seems like something you can do is to plug it to a powered USB hub. Try to see if that helps :) or SSH in.

**Comment by wiciu15** [comment]
Didnt have any usb hub on hand, but plugged keyboards vcc and gnd usb lines directly to power supply, and working fine so far. Thanks for advice ;)

**Comment by htruong** [comment]
Great to hear! Have fun!
