### ISSUE TITLE
OpenAuto crashed with RPi 3B+

### ISSUE THREAD

**Issue by agoNITE** [htruong/crankshaft#583]
- What phone do you have?
N/A

- What crankshaft version?
[Crankshaft OpenCarOS NG alpha-7.5 2022-06-29](https://github.com/opencardev/crankshaft/releases/tag/csng-alpha7.5)

- Steps to reproduce the bug, if you're planning to report a bug. Please indicate whether the bug is always repoducible.
Flash the image to a SD card, and boot it. Yes.

After boot, I get the following error:

```
Unfortunately, OpenAuto crashed.
Please report this indicident to Crankshaft
Restart in 5 seconds...
```

I'm using the original Raspberry Pi 7" touchscreen.

- Debug logs (both EGL and X11)
 [debug_EGL.zip](https://github.com/opencardev/crankshaft/files/9331073/debug_EGL.zip)
[debug_X11.zip](https://github.com/opencardev/crankshaft/files/9331074/debug_X11.zip)

**Comment by mario-correa** [comment]
same config here, and same error

**Comment by oakwoodMatt** [comment]
Same config and error here. Cannot boot.

**Comment by sylwesterszczepaniak** [comment]
Same error. Perhaps I can help debug/fix?

**Comment by mario-correa** [comment]
I fix it by downloading a previous release. It worked as expected.

**Comment by dirtball-official** [comment]
same issue

**Comment by matt2005** [comment]
which image are you using? the release has 2 images.
If you get a chance could you try the pi2 image, as the images may have gotten mixed up during the build.

**Comment by dirtball-official** [comment]
The pi2 image booted up and seems to work

**Comment by matt2005** [comment]
Great, i'm fixing the build issue and then I'll issue an updated image.

**Comment by agoNITE** [comment]
> Great, i'm fixing the build issue and then I'll issue an updated image.

Great! Luckily I didn't have any time to flash the previous build. So I'll be patiently waiting for the updated image, thanks!

**Comment by matt2005** [comment]
please try [2022.09.12.1](https://github.com/opencardev/crankshaft/releases/tag/v.2022.09.12.1) that should have the correct naming

**Comment by sylwesterszczepaniak** [comment]
Works out of the box. Thank you!
