### ISSUE TITLE
PI 4 2g

### ISSUE THREAD

**Issue by LukasKarer** [htruong/crankshaft#585]
Is there any chance to get crankshaft up and running on a pi 4 2g ram or is absolutely impossible?

**Comment by deejaypro** [comment]
Did you try it?
It should run on it see #426

**Comment by LukasKarer** [comment]
I tried, but it says "openauto crashed". No more info available.

**Comment by matt2005** [comment]
which image are you using? the release has 2 images.
If you get a chance could you try the pi2 image, as the images may have gotten mixed up during the build.

**Comment by matt2005** [comment]
please try [2022.09.12.1](https://github.com/opencardev/crankshaft/releases/tag/v.2022.09.12.1) that should have the correct naming
