### ISSUE TITLE
Attaching Oficial Tactil Display to Model A/B boards

### ISSUE THREAD

**Issue by cansi22** [htruong/crankshaft#59]
- What phone do you have? What OS version?
- Did you try to enable and run autoapp under X11 dev mode?  Follow this: https://github.com/htruong/crankshaft/wiki/Crankshaft-dev-mode
- Please provide any further information that you might find helpful.

https://github.com/raspberrypi/documentation/tree/master/hardware/display#attaching-to-model-ab-boards

DSI display autodetection is disabled by default on these boards. To enable detection, add the following line to /boot/config.txt:

ignore_lcd=0

**Comment by htruong** [comment]
Thanks for the tip. It's quite amazing that Crankshaft even works on these boards. The oldest I have is the A+ and I honestly didn't consciously have a concrete plan to make it work.
