### ISSUE TITLE
ETA on raspberry 3 b+

### ISSUE THREAD

**Issue by knotbeerdan** [htruong/crankshaft#60]
I apologize if this has already been asked and answered.

I realized I jumped the gun buying the newest board, but I figured it would be better to wait for it to be supported and take advantage of the upgrades it has. But I just wanted to ask if there was an eta for new pi 3 B+?

**Comment by htruong** [comment]
This weekend :)

**Comment by knotbeerdan** [comment]
Thank you for the fast response, and I look forward to the update!
