### ISSUE TITLE
cam_overlays problem with MJPG

### ISSUE THREAD

**Issue by Ramortada** [htruong/crankshaft#623]
I am using the latest crankshaft version. My sub rearcam isn't working with `cam_overlays.` Upon asking the meekys, the `cam_overlays` creator for a solution, he responded :  This is an issue with `crankshaft,` as they'll need to update to the cpp branch, which should support MJPG. 

Can you please look into the cpp branch?

Or, if anyone knows if it's possible to use a custom code to display my rearview camera.

Thank you for any help

**Comment by Jpower2023** [comment]
same here, need the cpp branch. If i install it myself with the common then it et crashed somehow.
