### ISSUE TITLE
Virtual machine on Crankshaft?

### ISSUE THREAD

**Issue by Ramortada** [htruong/crankshaft#624]
Is it possible to install a virtual machine on crankshaft to be able to open Rasbian image as guest operating system?

**Comment by kolonuk** [comment]
0. No. This project's focus is (legal) in-car entertainment, specifically Android Auto.

1. Why? What do you plan on doing?

2. Yes. Just like you would on a normal RPi. For noobs, check out https://raspberrytips.com/proxmox-on-raspberry-pi/. To caveat, a raspberry pi is not a PC.
