### ISSUE TITLE
Shoutout to the crankshaft dev team

### ISSUE THREAD

**Issue by seemebreakthis** [htruong/crankshaft#629]
For some reason the reddit sub is closed from public access (as far as writing new posts go), and I have no other convenient way of starting a discussion on Crankshaft.

I needed a quick way of testing if Android Auto works on my phone in my country.  Have a spare Pi4 lying around and a touchscreen too, so I went 'why not give it a try' and installed Crankshaft.

Surprised by how little manual work one has to do.  Just flash the image and the basic core functionality of Crankshaft works right out of the box.  Provided your phone is setup properly, just plug it into the usb port of the Pi, and you have Android Auto.

Wireless AA works too without too much hassle.  And on the Pi4B, I even quickly tested video playback, and things run smoothly.

The only obvious limitation from my brief usage is the lack of multi-touch.  But still I can totally see someone with 3d printing experience go create a frame that fits in the car, then install crankshaft as an AA permanent solution.  Easy setup, low maintenance, and low cost.

**Comment by kolonuk** [comment]
"install crankshaft as an AA permanent solution. Easy setup, low maintenance, and low cost".

I've done this in my old Pug 407. Luckily, the official RasPi touchscreen fitted VERY nicely in the higher-spec sat-nav surround. My guide: https://docs.google.com/document/d/1PqZVHNW8JBdjtaKXL-pYsXEVfQxqrHLk2BA_M7hiGPY/edit?usp=sharing

Unfortunately, I've moved on to a Pug 3008 with AA build in...
