### ISSUE TITLE
Sleep Mode

### ISSUE THREAD

**Issue by Maju3** [htruong/crankshaft#63]
Hi.
Just tested the 0.2.1 release.
I use a custom HDMI Touchscreen.
Now when disconnecting the phone after 30 seconds my Monitor shuts off.
Even when I reconnect the phone or type on the Touchscreen then my Monitor still is off.
The only way to make it work again is restarrting the PI.

**Comment by htruong** [comment]
Confirmed bug. Silly me was making some mistakes in assuming everyone has the official screen and not taking care of the edge case.

0.2.1-1 is out now and it should wake your custom screen up. Let me know if that works!

**Comment by Maju3** [comment]
Just tested 0.2.1-1 and now sleep mode WORKS and it Wakes up my Screen after replugin the phone.
GREAT WORK man!
Just take a look at the shutdown script please.
Shutdown does not work for me.

**Comment by htruong** [comment]
Great to hear :) Let's track the shutdown feature on a separate thread :)
