### ISSUE TITLE
OpenAuto does not show using DSI display

### ISSUE THREAD

**Issue by WGeu** [htruong/crankshaft#636]
If you need support: Please post on https://www.reddit.com/r/crankshaft/ as this is a bug tracker, not a support forum.

Note: Reporting issues not based on official published builds will be closed without any comment.

- What phone do you have?
Samsung A50

- What OS version?
Linux CRANKSHAFT-NG 5.10.103-V71+
- What crankshaft version?
2022-09-11 66525

- Steps to reproduce the bug, if you're planning to report a bug. Please indicate whether the bug is always repoducible.
Test setup that worked: Regular DELL display connected to HDMI 0 on mi Pi4. Connected phone and all worked as expected (I coulkd see Google Maps etc.)
Then I switched to the WaveShare 10.1" DSI display. Installed the drivers as described in the WoW of WaveShare. After the reboot, the Crankshaft GUI does show and all seems OK. But when I connect my phone I do see that it is connected (big tile shows USB Samsung Android), but the Open Auto doesn't show and I keep seeing the Crankshaft GUI (but it is locked)
On my phone it does show that I am connected to Android Auto.

- Please provide any further information that you might find helpful if available.
Nothing I can think of
[debug.zip](https://github.com/opencardev/crankshaft/files/12386091/debug.zip)

**Comment by abhilashdeshmukh** [comment]
I am facing the same issue with https://www.waveshare.com/wiki/8inch_DSI_LCD_(C), did you able to solve that last time?
