### ISSUE TITLE
Raspberry pi 5 support

### ISSUE THREAD

**Issue by gpatsiaouras** [htruong/crankshaft#652]
Hello,

I would like to help add compatibility with raspberry pi 5 but I don't know where to begin. I recently purchased an rpi 5 together with the raspberry pi 7" touchscreen. I get the message in boot screen that I should add `os_check=0` but still it doesn't boot.
Any help you can provide?

Georgios

**Comment by SuperMonkeyRules** [comment]
Im trying to do the same thing.
Did you ever get anywhere?

**Comment by nfmguimaraes** [comment]
there is any news about this or are there any alternatives?

**Comment by SuperMonkeyRules** [comment]
I dont think so :(
OpenAuto in raspbian might work?

**Comment by nfmguimaraes** [comment]
i'm trying this https://github.com/openDsh/dash right now and mange to work on pi5
