### ISSUE TITLE
Use only raspberry pi for android auto

### ISSUE THREAD

**Issue by smartaquarius10** [htruong/crankshaft#665]
Is it possible to use raspberry pi for sharing google maps and spotify in car screen without using and Android phone. 

What I want is install android auto app and crankshaft in raspberry pi and connect it the car via USB-A port. Just after this car screen automatically switch to android auto.

Is it possible to achieve this. Kindly suggest. Thank you.

Regards

**Comment by Geekyadz** [comment]
Sounds like you want Android Automotive, rather than Android Auto.

Android Auto needs your phone whereas I believe that Android Automotive does not require a phone.
