### ISSUE TITLE
Problem with 4.3inch DSI LCD  touchscreen

### ISSUE THREAD

**Issue by chingchong879** [htruong/crankshaft#668]
- What phone do you have? Zenfone9

- What OS version?  Android 14

- What crankshaft version? 2022-09-11 v

- What pi version? raspberry 4 pi

my screen is 4.3inch DSI LCD 800×480
When I inserted the SD card into raspberry and it installed successfully, but I couldn't get into the system, and the screen stayed stuck on black.
and i add this in to config.txt
max_usb_current=1
hdmi_group=2
hdmi_mode=87
hdmi_cvt 800 480 60 6 0 0 0
hdmi_drive=1
but still won't work

**Comment by Geekyadz** [comment]
What one do you have specifically? My one ( https://thepihut.com/products/4-3-dsi-capacitive-touchscreen-display-for-raspberry-pi-800x480?variant=41483994300611 ) has been working with changing any files

**Comment by chingchong879** [comment]
yes it's this one

Geekyadz ***@***.***> 於 2024年6月16日 週日 下午10:24 寫道：

**Comment by chingchong879** [comment]
maybe my sd is broken

淝水不入阿黑顏 ***@***.***> 於 2024年6月16日 週日 下午10:26 寫道：

**Comment by Geekyadz** [comment]
I'm not convinced it's your SD card. 

What I'm more convinced about is that it's the actual DSI cable itself or the lines you have added. 

Simple test: flash crankshaft to the SD card again and see if that works without adding anything to the files

**Comment by chingchong879** [comment]
okay i will try it later

Geekyadz ***@***.***> 於 2024年6月16日 週日 下午10:33 寫道：

**Comment by Geekyadz** [comment]
Any update on this?

**Comment by chingchong879** [comment]
hey can i add you on discord? Geekyadz

**Comment by chingchong879** [comment]
> I'm not convinced it's your SD card.
> 
> What I'm more convinced about is that it's the actual DSI cable itself or the lines you have added.
> 
> Simple test: flash crankshaft to the SD card again and see if that works without adding anything to the files

no cause i can see some system install but after that just stuck in black screen

**Comment by Geekyadz** [comment]
> > I'm not convinced it's your SD card.
> > 
> > What I'm more convinced about is that it's the actual DSI cable itself or the lines you have added.
> > 
> > Simple test: flash crankshaft to the SD card again and see if that works without adding anything to the files
> 
> no cause i can see some system install but after that just stuck in black screen

Then yes it does sound like it's the SD card if it's not even installing but you can see it doing its thing (ie the text)
