### ISSUE TITLE
Raspberry pi 5 issues? “Update the OS or set os_check=0  in config. txt to skip this check”

### ISSUE THREAD

**Issue by Paako89** [htruong/crankshaft#671]
Hi there. I tried to install crankshaft on raspberry pi5. However when I try to boot I get this error 
“The installed operating system (OS) does not indicate support for Raspberry Pi 5
Update the OS or set os_check=0  in config. txt to skip this check” .
I can’t see that option on the config file. So I tried adding it in my self and saving the config file. 
once inserted in the pi on boot I only see black screen and nothing else.
![IMG_1424](https://github.com/opencardev/crankshaft/assets/131194679/0755e7ab-470c-4e26-8a1e-289b8edaa8b6)

**Comment by Geekyadz** [comment]
That's cos it's not made for the Raspberry Pi 5, which has higher power requirements than the Pi 4
