### ISSUE TITLE
Rotate screen from GUI menu for some Pi screen cases

### ISSUE THREAD

**Issue by jlukanc1** [htruong/crankshaft#7]
Some cases have the screen upside-down, this makes it tedious to leave the Android Auto launcher and modify the boot.txt. A dropdown menu can be added for the 4 display orientations in the "Display" tab.

Edit: Clarified title

**Comment by htruong** [comment]
I actually thought of a good idea ( to me ;-) ) to achieve this. Next version will allow you to put a jumper in the headers to rotate the screen. :)

**Comment by htruong** [comment]
V0.1.1 is uploading right now. This issue is fixed. Relevant changelog:

```
- Allows screen flipping when putting a jumper on GPIO21/Ground
      (Pin 39-40 - that's the last row of pins)
```
