### ISSUE TITLE
Stuck in English UK!

### ISSUE THREAD

**Issue by Subwater** [htruong/crankshaft#73]
They keyboard is stuck in English UK!  I have tried everything you would normally do on Raspbian... no success.  

To fix the problem I have to run `sudo apt install console-common && sudo dpkg-reconfigure console-data` then proceed through a terminal gui to fix the issue everytime.

**Comment by stramazzo** [comment]
I have a simular issue with a Logitech wireless keyboard. But my conclusion, brausing the Internet was that It was a common issue with some Logitech wireless keyboard and not Crankshaft related.

**Comment by htruong** [comment]
Glad (sad) that it's the hardware's fault (weird that they did that though).

**Comment by alandoyle95** [comment]
I can confirm this bug!  Software related on wired, and wireless keyboards.
