### ISSUE TITLE
Crankshaft shuts down immediately after NTP time sync

### ISSUE THREAD

**Issue by snailium** [htruong/crankshaft#77]
- Enabled dev mode
- SSH'ed to Crankshaft
- Setup NTP to sync time (time jumped from 2016 to 2018)
- Crankshaft shuts down immediately after boot/reboot

I guess problem is the auto-shutdown script in the latest build.

Here is what I got right after NTP is installed.

```
Setting up ntp (1:4.2.8p10+dfsg-3+deb9u2) ...

Broadcast message from root@crankshaft (Thu 2016-11-03 13:21:45 EDT):

The system is going down for poweroff at Thu 2016-11-03 13:31:45 EDT!

Processing triggers for libc-bin (2.24-11+deb9u3) ...
Processing triggers for systemd (232-25+deb9u2) ...
pi@crankshaft:~ $
Broadcast message from root@crankshaft (Mon 2018-04-16 05:30:14 EDT):

The system is going down for poweroff NOW!
```

Here is what I got if I'm fast enough to login SSH.

```
pi@crankshaft:~ $
Broadcast message from root@crankshaft (Mon 2018-04-16 05:31:03 EDT):

The system is going down for poweroff NOW!

```

**Comment by htruong** [comment]
Ahaha! Oh yeah, do a `shutdown -c` before you sync the time :) When it starts up, it sets a 15 minutes shutdown in the future just in case something starts up the Pi and doesn't shut it down (it will drain the car battery). When you plug in the phone, it cancels the shutdown timer. :)

**Comment by htruong** [comment]
So... tag this as `wontfix`?

**Comment by htruong** [comment]
Oh I see. So ntp syncs the time after the timer was set on every start up. This isn't nice. I guess we can somehow make it so the crankshaft startup script waits for ntp to finish before it sets the timer.

**Comment by snailium** [comment]
Maybe it is better to disable auto-shutoff in dev mode?

**Comment by htruong** [comment]
Done. Edit the `/boot/crankshaft/crankshaft_env.sh` and set that `NO_CONNECTION_POWEROFF_MINS` to `0`, and it won't auto-shutoff.
