### ISSUE TITLE
openauto won't start after successfull build from source

### ISSUE THREAD

**Issue by hawkeyexp** [htruong/crankshaft#87]
After solving the qt5 build errors i got a new bug whil booting the resulting system:

openauto.sh[594]: /usr/local/bin/autoapp: error while loading shared libraries: libGLESv2.so: cannot open shared object file: No such file or directory

**Comment by hawkeyexp** [comment]
`sudo apt install libraspberrypi-bin` is still there
`sudo rpi-update` solved the problem but first i had to install ntp cause it won't run without synced time :-)
I will add the ntp to scripts in debug mode.
But next prob is in the pipe - device connected and nothing happes but device says connected to car.

**Comment by htruong** [comment]
Oh, that's a separate one. I have that problem for some reason now as well, but haven't had time to figure out what that was that prevented it to work. Did you do the udev rules?

Try to pull the openauto and aasdl.so and such from the latest image. It is a build that works.

**Comment by hawkeyexp** [comment]
Will try it.
i noticed this:
`Failed to load module "module-mmkbd-evdev" (argument: "device=/dev/gpio2kbd"): initialization failed.`

**Comment by hawkeyexp** [comment]
i have identified the prob - if i switch from rtaudio to qt in settings it works !
